import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

const MOCKUPS_DIR = "src/components/mockups";
const GENERATED_MODULE = "src/.generated/mockup-components.ts";

function walkPreviewFiles(directory: string, root: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      return entry.name.startsWith("_") ? [] : walkPreviewFiles(absolute, root);
    }
    return entry.name.endsWith(".tsx") && !entry.name.startsWith("_")
      ? [path.relative(root, absolute)]
      : [];
  });
}

export function mockupPreviewPlugin(): Plugin {
  let root = "";

  function refresh(): void {
    const mockupsRoot = path.join(root, MOCKUPS_DIR);
    mkdirSync(mockupsRoot, { recursive: true });
    const files = walkPreviewFiles(mockupsRoot, path.join(root, "src"));
    const entries = files
      .map((file) => {
        const sourcePath = `./${file.replaceAll(path.sep, "/")}`;
        const importPath = path.posix.relative(
          "src/.generated",
          `src/${file.replaceAll(path.sep, "/")}`,
        );
        return `  ${JSON.stringify(sourcePath)}: () => import(${JSON.stringify(`./${importPath}`)})`;
      })
      .join(",\n");
    const content = [
      "// Generated by mockupPreviewPlugin.ts.",
      "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
      "export const modules: ModuleMap = {",
      entries,
      "};",
      "",
    ].join("\n");
    const generatedPath = path.join(root, GENERATED_MODULE);
    mkdirSync(path.dirname(generatedPath), { recursive: true });
    writeFileSync(generatedPath, content);
  }

  return {
    name: "mockup-preview",
    enforce: "pre",
    configResolved(config) {
      root = config.root;
    },
    buildStart() {
      refresh();
    },
    configureServer() {
      refresh();
    },
  };
}