/**
 * Read-only HTTP export verifier.
 *
 * This is an isolated local Express harness, not a browser or deployed-app
 * check. It mounts the real report and analytics routers, replaces only their
 * session lookup with an in-memory authorized request context, and keeps the
 * real ADMIN role middleware in place. Every report read, including reads
 * made by the route handlers, is forced through one READ ONLY REPEATABLE READ
 * PostgreSQL client. No session, user, fixture, initializer, or write is
 * created.
 *
 * The harness downloads the actual composed XLSX/PDF route bytes, obtains the
 * individual JSON sources used by the screen, composes those source payloads
 * without printing rows, and compares:
 *
 *   screen sources -> composed builder -> downloaded workbook/PDF
 *
 * Five normal views and five comparison views are exercised when the live
 * header catalog has at least two eligible physical locations. Set
 * REPORT_EXPORT_FOCUS to a comma-separated subset (for example
 * ventas-normal,que-comprar-normal) when a shorter evidence pass is needed.
 * PDF text/table checks use pdftotext or fitz independently; no second PDF
 * generated by this module is treated as the expected artifact.
 * The report contains counts, IDs, hashes, byte lengths, and parser/render
 * metrics only.
 * Private rows never enter a report, log, or committed artifact.
 *
 * Optional fitz inspection uses an already installed python3/PyMuPDF only.
 * The script never installs dependencies. Set REPORT_EXPORT_WRITE_ARTIFACTS=1
 * to retain one representative global Ventas XLSX/PDF pair under
 * reports/exports (mode 0600), including first/wide/X04/last representative
 * PNGs for each case. The directory is local-only and gitignored.
 */

import { createHash } from "node:crypto";
import { createServer } from "node:http";
import { execFileSync } from "node:child_process";
import express, { type Express } from "express";
import ExcelJS from "exceljs";
import { chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { chmodSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { inflateSync } from "node:zlib";

import { pool } from "@workspace/db";
import { toExcelNumber } from "@workspace/number-format";
import {
  buildComposedReport,
  comparisonCharts,
  comparisonTable,
  type ComposedReport,
  type ComposedReportInput,
} from "../lib/reportes-composed-export";
import { normalizeExportTables, type ExportTable } from "../lib/report-export";
import {
  formatReportFilters,
  formatReportRange,
  formatReportValue,
  hasMeaningfulTotals,
  labelForReportKey,
  reportTotalLabel,
  type ReportValueKind,
} from "../lib/report-presentation";
import { accountedDocumentAt, accountedDocumentPredicate } from "../lib/accounted-document";
import { controlOperativoRoleGate } from "../routes/reportes";

type AnyRecord = Record<string, any>;
type Content = {
  kpis: any[];
  charts: any[];
  tables: any[];
  warnings: string[];
  alerts?: any[];
};
type AuthMode = "admin" | "nonadmin";
type CaseMode = "normal" | "comparar";
type SourceResponse = AnyRecord;

const VIEWS = ["ventas", "que-comprar", "utilidad", "clientes", "control-operativo"] as const;
type View = (typeof VIEWS)[number];
const REPORT_SOURCES: Record<View, string[]> = {
  ventas: ["ventas"],
  "que-comprar": ["que-comprar", "inventario", "mapas-calor", "color", "compras"],
  utilidad: ["utilidad"],
  clientes: ["clientes", "pagos-dirigidos"],
  "control-operativo": ["control-operativo"],
};
const WRITE_SQL = /\b(INSERT|UPDATE|DELETE|MERGE|ALTER|CREATE|DROP|TRUNCATE|GRANT|REVOKE|COMMENT|VACUUM|REFRESH|CALL|DO)\b/i;
const REPORT_PATH = resolve(fileURLToPath(import.meta.url), "../../../../..", "reports/export-download-verification.md");
const EXPORT_DIR = resolve(fileURLToPath(import.meta.url), "../../../../..", "reports/exports");

function stable(value: unknown): string {
  if (value === undefined) return "undefined";
  if (value === null) return "null";
  if (value instanceof Date) return JSON.stringify(value.toISOString());
  if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`;
  if (typeof value === "object") {
    const record = value as AnyRecord;
    return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stable(record[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function hash(value: unknown): string {
  return createHash("sha256").update(stable(value)).digest("hex");
}

function bytesHash(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function asContent(value: AnyRecord): Content {
  return {
    kpis: Array.isArray(value.kpis) ? value.kpis : [],
    charts: Array.isArray(value.charts) ? value.charts : [],
    tables: Array.isArray(value.tables) ? value.tables : [],
    warnings: Array.isArray(value.warnings) ? value.warnings : [],
    ...(Array.isArray(value.alerts) ? { alerts: value.alerts } : {}),
  };
}

function appendContent(sources: Content[]): Content {
  const alerts = sources.flatMap((source) => source.alerts ?? []);
  return {
    kpis: sources.flatMap((source) => source.kpis),
    charts: sources.flatMap((source) => source.charts),
    tables: sources.flatMap((source) => source.tables),
    warnings: sources.flatMap((source) => source.warnings),
    ...(alerts.length ? { alerts } : {}),
  };
}

function decorate(content: Content, index: number, site: { id: number; label: string }): Content {
  const prefix = `sitio-${site.id}`;
  const frameLabel = `${site.label} (#${site.id})`;
  const decorateBlock = (block: AnyRecord) => ({
    ...block,
    id: `${prefix}-${String(block.id ?? "bloque")}`,
    title: block.title ? `${frameLabel} · ${block.title}` : block.title,
    siteId: site.id,
    siteLabel: site.label,
  });
  return {
    kpis: content.kpis.map(decorateBlock),
    charts: content.charts.map(decorateBlock),
    tables: content.tables.map(decorateBlock),
    warnings: content.warnings.map((warning) => `[${frameLabel}] ${warning}`),
    ...(content.alerts ? { alerts: content.alerts } : {}),
  };
}

function routeQuery(input: Record<string, unknown>): string {
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined || value === null || value === "") continue;
    query.set(key, Array.isArray(value) ? value.join(",") : String(value));
  }
  return query.toString();
}

function sourceQuery(base: AnyRecord, siteId?: number): AnyRecord {
  return {
    periodo: base.periodo,
    desde: base.desde,
    hasta: base.hasta,
    ...(base.modalidad ? { modalidad: base.modalidad } : {}),
    ...(siteId === undefined ? {} : { ubicacionIds: String(siteId) }),
  };
}

function exportQuery(base: AnyRecord, mode: CaseMode): AnyRecord {
  return {
    ...base,
    margenUmbral: 15,
    coberturaCritico: 7,
    coberturaBajo: 15,
    coberturaNormal: 60,
    coberturaExceso: 90,
    modo: mode,
    umbralCorte: 0,
    umbralTienda: 0,
    agrupacion: "semana",
  };
}

function cashContent(cash: AnyRecord, base: AnyRecord, siteId?: number): Content {
  const resumen = cash.resumen ?? {};
  const groupColumns = [
    { key: "id", label: "Id", kind: "count" },
    { key: "nombre", label: "Nombre", kind: "text" },
    { key: "cortes", label: "Cortes", kind: "count" },
    { key: "exactos", label: "Exactos", kind: "count" },
    { key: "faltantes", label: "Faltantes", kind: "count" },
    { key: "sobrantes", label: "Sobrantes", kind: "count" },
    { key: "importeFaltantes", label: "Importe faltantes", kind: "money", economic: true },
    { key: "importeSobrantes", label: "Importe sobrantes", kind: "money", economic: true },
    { key: "diferenciaNeta", label: "Diferencia neta", kind: "money", economic: true },
    { key: "diferenciaAbsoluta", label: "Diferencia absoluta", kind: "money", economic: true },
    { key: "promedio", label: "Promedio", kind: "money", economic: true },
    { key: "porcentajeExactos", label: "% exactos", kind: "percentage", economic: true },
  ];
  const scoped = siteId === undefined ? undefined : siteId;
  const dateQuery = new URLSearchParams({
    desde: String(base.desde),
    hasta: String(base.hasta),
  });
  if (scoped !== undefined) dateQuery.set("ubicacionId", String(scoped));
  const alerts = (cash.alertas ?? []).map((alert: AnyRecord) => ({
    ...alert,
    href: `/caja/cortes?sesionId=${alert.sesionId}&${dateQuery.toString()}`,
  }));
  const trendRows = (cash.tendencia ?? []).map((row: AnyRecord) => ({
    fecha: row.fecha,
    importe: Number(row.importe),
    diferenciaAbsoluta: Number(row.diferenciaAbsoluta),
    cortes: Number(row.cortes),
    exactos: Number(row.exactos),
    porcentajeExactos: Number(row.porcentajeExactos),
  }));
  const warning = alerts.map((alert: AnyRecord) =>
    `Alerta de diferencia de caja [${alert.tipo}] sesión ${alert.sesionId}: ${alert.mensaje} · Importe ${alert.importe}`,
  );
  const numberKpi = (id: string, label: string, value: any, kind: string) => ({
    id, label, value, kind,
    ...(kind === "money" || kind === "percentage" ? { economic: true } : {}),
  });
  return {
    kpis: [
      numberKpi("cortes-caja", "Cortes de caja", resumen.cortes, "count"),
      numberKpi("cortes-exactos", "Cortes exactos", resumen.exactos, "count"),
      numberKpi("faltantes-caja", "Impacto faltantes", resumen.importeFaltantes, "money"),
      numberKpi("sobrantes-caja", "Impacto sobrantes", resumen.importeSobrantes, "money"),
      numberKpi("diferencia-neta-caja", "Diferencia neta del periodo", resumen.diferenciaNeta, "money"),
      numberKpi("diferencia-absoluta-caja", "Diferencia absoluta del periodo", resumen.diferenciaAbsoluta, "money"),
      numberKpi("exactitud-caja", "Porcentaje de exactitud", resumen.porcentajeExactos, "percentage"),
    ],
    charts: [
      {
        id: "diferencias-caja-tendencia",
        title: "Tendencia de Diferencia Neta",
        type: "line",
        categoryKey: "fecha",
        series: [
          { key: "importe", label: "Diferencia neta", kind: "money", economic: true },
          { key: "diferenciaAbsoluta", label: "Diferencia absoluta", kind: "money", economic: true },
        ],
        rows: trendRows,
      },
      {
        id: "diferencias-caja-exactitud",
        title: "Porcentaje de Exactitud",
        type: "line",
        categoryKey: "fecha",
        series: [{ key: "porcentajeExactos", label: "% exactos", kind: "percentage", economic: true }],
        rows: trendRows,
      },
    ],
    tables: [
      {
        id: "diferencias-por-cajero",
        title: "Diferencias por Cajero",
        columns: groupColumns,
        rows: cash.porCajero ?? [],
        totals: { nombre: "Total General", ...resumen },
      },
      {
        id: "diferencias-por-tienda",
        title: "Diferencias por Tienda",
        columns: groupColumns,
        rows: cash.porTienda ?? [],
        totals: { nombre: "Total General", ...resumen },
      },
    ],
    warnings: warning,
    alerts,
  };
}

function sourceCoverage(content: Content) {
  return {
    kpis: content.kpis.length,
    charts: content.charts.length,
    tables: content.tables.length,
    rows: content.tables.reduce((sum, table) => sum + (Array.isArray(table.rows) ? table.rows.length : 0), 0),
    totals: content.tables.filter((table) => table.totals && typeof table.totals === "object").length,
    tableIds: content.tables.map((table) => String(table.id)),
    chartIds: content.charts.map((chart) => String(chart.id)),
    contentHash: hash(content),
  };
}

function normalizeComparisonPayload(value: AnyRecord): AnyRecord {
  const day = (item: unknown) => typeof item === "string" ? item.slice(0, 10) : item;
  return {
    ...value,
    tiendas: (value.tiendas ?? []).map((store: AnyRecord) => ({
      ...store,
      mejorDia: store.mejorDia ? { ...store.mejorDia, fecha: day(store.mejorDia.fecha) } : store.mejorDia,
      peorDia: store.peorDia ? { ...store.peorDia, fecha: day(store.peorDia.fecha) } : store.peorDia,
    })),
    ventasPorFecha: (value.ventasPorFecha ?? []).map((point: AnyRecord) => ({
      ...point,
      fecha: day(point.fecha),
    })),
  };
}

function xlsxCell(value: any): any {
  if (value instanceof Date) return value.toISOString();
  if (value && typeof value === "object" && "text" in value) return value.text;
  return value ?? null;
}

function excelValue(column: AnyRecord, value: any): any {
  if (value === undefined || value === null) return null;
  if (["money", "quantity", "count", "percentage", "days"].includes(String(column.kind)) && value !== "Pendiente") {
    return toExcelNumber(value);
  }
  return value;
}

function worksheetName(title: string, used: Set<string>): string {
  const base = title.slice(0, 31) || "Hoja";
  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) {
    const marker = ` ${suffix}`;
    candidate = `${base.slice(0, 31 - marker.length)}${marker}`;
    suffix += 1;
  }
  used.add(candidate);
  return candidate;
}

function sheetRows(sheet: ExcelJS.Worksheet, width: number, first: number, last: number): any[][] {
  const rows: any[][] = [];
  for (let rowNumber = first; rowNumber <= last; rowNumber += 1) {
    rows.push(Array.from({ length: width }, (_, index) => xlsxCell(sheet.getRow(rowNumber).getCell(index + 1).value)));
  }
  return rows;
}

async function inspectWorkbook(bytes: Uint8Array, data: ComposedReport): Promise<AnyRecord> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(bytes as any);
  const normalized = normalizeExportTables(String(data.section), data.activeFilters, data.tables as ExportTable[]);
  const used = new Set<string>(["Periodo", "Indicadores"]);
  const expectedSheets: string[] = ["Periodo", "Indicadores"];
  const mismatches: string[] = [];
  const meta = workbook.getWorksheet("Periodo");
  if (!meta || xlsxCell(meta.getCell("B1").value) !== String(data.section)) mismatches.push("Periodo.section");
  if (!meta || xlsxCell(meta.getCell("A1").value) !== "Reporte") mismatches.push("Periodo.header");
  if (!meta || xlsxCell(meta.getCell("B3").value) !== formatReportRange(data.range)) mismatches.push("Periodo.range");
  const filterText = meta ? String(xlsxCell(meta.getCell("B4").value) ?? "") : "";
  if (
    !filterText ||
    filterText.includes("previousDesde") ||
    filterText.includes("yearAgoDesde") ||
    filterText.includes("ubicacionIds=") ||
    filterText.includes("productoIds=") ||
    filterText.includes("{")
  ) {
    mismatches.push("Periodo.filters-readable");
  }
  for (const filter of formatReportFilters(data.activeFilters)) {
    const label = filter.split(":")[0];
    if (!filterText.includes(label)) mismatches.push(`Periodo.filter-label:${label}`);
  }
  const indicator = workbook.getWorksheet("Indicadores");
  const expectedIndicators = (data.kpis as any[]).map((item) => [item.label, excelValue(item, item.value)]);
  if (!indicator) mismatches.push("Indicadores.missing");
  else {
    const actual = sheetRows(indicator, 2, 2, indicator.rowCount);
    if (!equalValues(actual, expectedIndicators)) mismatches.push("Indicadores.values");
    (data.kpis as AnyRecord[]).forEach((item, index) => {
      if (item.kind === "percentage" && indicator.getCell(index + 2, 2).numFmt !== '0.00"%"') {
        mismatches.push(`Indicadores.percentage-format:${String(item.id ?? index)}`);
      }
    });
  }
  for (const table of normalized) {
    const name = worksheetName(table.title, used);
    expectedSheets.push(name);
    const sheet = workbook.getWorksheet(name);
    if (!sheet) {
      mismatches.push(`table:${table.id}:missing`);
      continue;
    }
    const headers = table.columns.map((column) => column.label);
    const rows = table.rows.map((row) => table.columns.map((column) => excelValue(column, row[column.key])));
    const totals = hasMeaningfulTotals(table.totals)
      ? [table.columns.map((column) => excelValue(column, table.totals[column.key]))]
      : [];
    if (totals.length) {
      const totalLabel = reportTotalLabel(table.columns, table.totals);
      const labelColumn = totalLabel ? table.columns.findIndex((column) => column.key === totalLabel.key) : -1;
      if (totalLabel && labelColumn >= 0 && totals[0]![labelColumn] == null) totals[0]![labelColumn] = totalLabel.value;
    }
    if (!equalValues(sheetRows(sheet, table.columns.length, 1, 1), [headers])) mismatches.push(`table:${table.id}:headers`);
    if (!equalValues(sheetRows(sheet, table.columns.length, 2, 1 + rows.length), rows)) mismatches.push(`table:${table.id}:rows`);
    if (totals.length && !equalValues(sheetRows(sheet, table.columns.length, 2 + rows.length, 2 + rows.length), totals)) mismatches.push(`table:${table.id}:totals`);
    if (!totals.length && sheet.rowCount > 1 + rows.length) mismatches.push(`table:${table.id}:empty-total-row`);
    for (const column of table.columns) {
      if (["money", "quantity", "count", "percentage", "days"].includes(column.kind)) {
        const columnIndex = table.columns.indexOf(column) + 1;
        if (column.kind === "percentage" && sheet.getColumn(columnIndex).numFmt !== '0.00"%"') {
          mismatches.push(`table:${table.id}:percentage-format:${column.key}`);
        }
        for (let rowNumber = 2; rowNumber <= 1 + rows.length; rowNumber += 1) {
          const value = xlsxCell(sheet.getRow(rowNumber).getCell(columnIndex).value);
          if (value !== null && value !== "Pendiente" && typeof value !== "number") {
            mismatches.push(`table:${table.id}:non-numeric:${column.key}`);
          }
        }
      }
    }
  }
  for (const chart of (data.charts as any[])) {
    const name = worksheetName(`Grafico ${chart.title}`, used);
    expectedSheets.push(name);
    const sheet = workbook.getWorksheet(name);
    const columns = [
      { key: chart.categoryKey, label: labelForReportKey(chart.categoryKey), kind: "text" },
      ...(chart.series ?? []).map((series: AnyRecord) => ({ key: series.key, label: series.label, kind: series.kind ?? "text" })),
    ];
    const expectedRows = (chart.rows ?? []).map((row: AnyRecord) => columns.map((column) => excelValue(column, row[column.key])));
    if (!sheet) {
      mismatches.push(`chart:${chart.id}:missing`);
      continue;
    }
    if (!equalValues(sheetRows(sheet, columns.length, 1, 1), [columns.map((column) => column.label)])) mismatches.push(`chart:${chart.id}:headers`);
    if (!equalValues(sheetRows(sheet, columns.length, 2, 1 + expectedRows.length), expectedRows)) mismatches.push(`chart:${chart.id}:rows`);
    columns.forEach((column, index) => {
      if (column.kind === "percentage" && sheet.getColumn(index + 1).numFmt !== '0.00"%"') {
        mismatches.push(`chart:${chart.id}:percentage-format:${column.key}`);
      }
    });
  }
  if ((data.warnings as string[]).length) {
    const name = worksheetName("Avisos", used);
    expectedSheets.push(name);
    const sheet = workbook.getWorksheet(name);
    const expected = (data.warnings as string[]).map((warning) => [warning]);
    if (!sheet || !equalValues(sheetRows(sheet, 1, 2, 1 + expected.length), expected)) mismatches.push("Avisos.values");
  }
  if (Array.isArray(data.alerts) && data.alerts.length) {
    const name = worksheetName("Alertas", used);
    expectedSheets.push(name);
    const sheet = workbook.getWorksheet(name);
    const expected = data.alerts.map((alert: AnyRecord) => ["sesionId", "tipo", "mensaje", "importe", "href"].map((key) => alert[key] ?? null));
    if (!sheet || !equalValues(sheetRows(sheet, 5, 2, 1 + expected.length), expected)) mismatches.push("Alertas.values");
  }
  const actualSheets = workbook.worksheets.map((sheet) => sheet.name);
  if (!equalValues(actualSheets, expectedSheets)) mismatches.push("sheet-order-or-count");
  return {
    validZip: Buffer.from(bytes).subarray(0, 2).toString("ascii") === "PK",
    sheetCount: workbook.worksheets.length,
    sheetNamesHash: hash(actualSheets),
    mismatches,
    expectedTableCount: normalized.length,
    expectedChartCount: (data.charts as any[]).length,
    expectedKpiCount: (data.kpis as any[]).length,
    expectedRowCount: normalized.reduce((sum, table) => sum + table.rows.length, 0),
  };
}

function pdfMetrics(bytes: Buffer): AnyRecord {
  const directory = execFileSync("mktemp", ["-d", join(tmpdir(), "report-export-pdf-XXXXXX")], { encoding: "utf8" }).trim();
  const path = join(directory, "download.pdf");
  const pageCount = (bytes.toString("latin1").match(/\/Type \/Page\b/g) ?? []).length;
  try {
    writeFileSync(path, bytes, { mode: 0o600 });
    const script = [
      "import fitz,hashlib,json,sys",
      "doc=fitz.open(sys.argv[1])",
      "text='\\n'.join(page.get_text() for page in doc)",
      "rendered=0",
      "sizes=[]",
      "for page in doc:",
      " pix=page.get_pixmap(matrix=fitz.Matrix(1,1),alpha=False)",
      " rendered+=1",
      " sizes.append([pix.width,pix.height])",
      "print(json.dumps({'fitz':True,'pageCount':len(doc),'textChars':len(text),'textHash':hashlib.sha256(text.encode()).hexdigest(),'renderedPages':rendered,'renderSizes':sizes}))",
    ].join("\n");
    const output = execFileSync("python3", ["-c", script, path], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    let text = "";
    try {
      text = execFileSync("pdftotext", [path, "-"], {
        encoding: "utf8",
        maxBuffer: 20 * 1024 * 1024,
        stdio: ["ignore", "pipe", "ignore"],
      });
    } catch {
      // fitz still supplies page/text metrics when pdftotext is absent.
    }
    return { ...JSON.parse(output), text };
  } catch {
    let text = "";
    let renderedPages = 0;
    const renderSizes: number[][] = [];
    try {
      text = execFileSync("pdftotext", [path, "-"], {
        encoding: "utf8",
        maxBuffer: 20 * 1024 * 1024,
        stdio: ["ignore", "pipe", "ignore"],
      });
      const prefix = join(directory, "page");
      const pagesToRender = [...new Set([1, pageCount].filter((page) => page > 0))];
      for (const page of pagesToRender) {
        execFileSync("pdftoppm", ["-f", String(page), "-l", String(page), "-png", "-r", "72", path, `${prefix}-${page}`], {
          stdio: ["ignore", "ignore", "ignore"],
        });
      }
      const rendered = readdirSync(directory)
        .filter((name) => name.startsWith("page-") && name.endsWith(".png"))
        .sort();
      renderedPages = rendered.length;
      for (const name of rendered) {
        const png = readFileSync(join(directory, name));
        if (png.toString("ascii", 0, 8) === "\x89PNG\r\n\x1a\n") {
          renderSizes.push([png.readUInt32BE(16), png.readUInt32BE(20)]);
        }
      }
    } catch {
      // Keep the dependency-free page count below if either command is unavailable.
    }
    return {
      fitz: false,
      pageCount,
      textChars: text.length,
      textHash: text ? createHash("sha256").update(text).digest("hex") : null,
      text,
      renderedPages,
      renderSizes,
    };
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

type PdfBBoxWord = {
  text: string;
  xMin: number;
  xMax: number;
  yMin: number;
  yMax: number;
};

type PdfBBoxPage = {
  width: number;
  height: number;
  words: PdfBBoxWord[];
};

function decodeXml(value: string): string {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_match, code: string) => String.fromCodePoint(Number.parseInt(code, 16)))
    .replace(/&#([0-9]+);/g, (_match, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&apos;/g, "'");
}

function geometryKey(value: unknown): string {
  return String(value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

function parsePdfBBox(bytes: Buffer): PdfBBoxPage[] {
  const directory = execFileSync("mktemp", ["-d", join(tmpdir(), "report-export-bbox-XXXXXX")], { encoding: "utf8" }).trim();
  const path = join(directory, "download.pdf");
  try {
    writeFileSync(path, bytes, { mode: 0o600 });
    const output = execFileSync("pdftotext", ["-bbox", path, "-"], {
      encoding: "utf8",
      maxBuffer: 50 * 1024 * 1024,
      stdio: ["ignore", "pipe", "ignore"],
    });
    const pages: PdfBBoxPage[] = [];
    const pagePattern = /<page\s+width="([^"]+)"\s+height="([^"]+)"[^>]*>([\s\S]*?)<\/page>/g;
    let pageMatch: RegExpExecArray | null;
    while ((pageMatch = pagePattern.exec(output))) {
      const words: PdfBBoxWord[] = [];
      const wordPattern = /<word\s+xMin="([^"]+)"\s+yMin="([^"]+)"\s+xMax="([^"]+)"\s+yMax="([^"]+)"[^>]*>([\s\S]*?)<\/word>/g;
      let wordMatch: RegExpExecArray | null;
      while ((wordMatch = wordPattern.exec(pageMatch[3]!))) {
        const text = decodeXml(wordMatch[5]!).replace(/\s+/g, " ").trim();
        if (!text) continue;
        words.push({
          text,
          xMin: Number(wordMatch[1]),
          yMin: Number(wordMatch[2]),
          xMax: Number(wordMatch[3]),
          yMax: Number(wordMatch[4]),
        });
      }
      pages.push({
        width: Number(pageMatch[1]),
        height: Number(pageMatch[2]),
        words,
      });
    }
    if (!pages.length) throw new Error("pdftotext -bbox no devolvió páginas.");
    return pages;
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

function phraseWords(value: unknown): string[] {
  const key = geometryKey(value);
  return key ? key.split(" ") : [];
}

function pageText(page: PdfBBoxPage): string {
  return page.words.map((word) => word.text).join(" ");
}

type PdfPhraseOccurrence = {
  pageIndex: number;
  words: PdfBBoxWord[];
};

type PdfVectorRect = {
  x: number;
  y: number;
  width: number;
  height: number;
};

type PdfVectorPage = {
  width: number;
  height: number;
  rects: PdfVectorRect[];
};

type PdfVectorRow = {
  y: number;
  height: number;
  cells: PdfVectorRect[];
};

function findPhraseOccurrences(pages: PdfBBoxPage[], value: unknown): PdfPhraseOccurrence[] {
  const expected = phraseWords(value);
  if (!expected.length) return [];
  const occurrences: PdfPhraseOccurrence[] = [];
  for (let pageIndex = 0; pageIndex < pages.length; pageIndex += 1) {
    const words = pages[pageIndex]!.words.filter((word) => geometryKey(word.text));
    for (let index = 0; index <= words.length - expected.length; index += 1) {
      const candidate = words.slice(index, index + expected.length);
      if (candidate.map((word) => geometryKey(word.text)).join(" ") !== expected.join(" ")) continue;
      occurrences.push({ pageIndex, words: candidate });
    }
  }
  return occurrences;
}

function parsePdfVectorPages(bytes: Buffer): PdfVectorPage[] {
  const source = bytes.toString("latin1");
  const streams = new Map<number, Buffer>();
  const streamPattern = /(\d+)\s+0\s+obj\s*<<((?:(?!\bendobj\b)[\s\S])*?)>>\s*stream\r?\n/g;
  let streamMatch: RegExpExecArray | null;
  while ((streamMatch = streamPattern.exec(source))) {
    const lengthMatch = streamMatch[2]!.match(/\/Length\s+(\d+)/);
    if (!lengthMatch) continue;
    const start = streamMatch.index + streamMatch[0].length;
    const raw = Buffer.from(source.slice(start, start + Number(lengthMatch[1])), "latin1");
    try {
      streams.set(Number(streamMatch[1]), /\/Filter\s*\/FlateDecode/.test(streamMatch[2]!)
        ? inflateSync(raw)
        : raw);
    } catch {
      // A non-page stream (for example an embedded font) is not geometry.
    }
  }
  const pages: PdfVectorPage[] = [];
  const pagePattern = /(\d+)\s+0\s+obj\s*<<([\s\S]*?)>>\s*endobj/g;
  let pageMatch: RegExpExecArray | null;
  while ((pageMatch = pagePattern.exec(source))) {
    const dictionary = pageMatch[2]!;
    if (!/\/Type\s*\/Page\b/.test(dictionary)) continue;
    const contents = dictionary.match(/\/Contents\s+(\d+)\s+0\s+R/);
    const mediaBox = dictionary.match(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)/);
    const stream = contents ? streams.get(Number(contents[1])) : undefined;
    if (!stream || !mediaBox) continue;
    const text = stream.toString("latin1");
    const rectangles: PdfVectorRect[] = [];
    const number = "[-+]?(?:\\d+(?:\\.\\d+)?|\\.\\d+)";
    const rectPattern = new RegExp(`(${number})\\s+(${number})\\s+(${number})\\s+(${number})\\s+re\\b`, "g");
    let rectMatch: RegExpExecArray | null;
    while ((rectMatch = rectPattern.exec(text))) {
      const rectangle = {
        x: Number(rectMatch[1]),
        y: Number(rectMatch[2]),
        width: Number(rectMatch[3]),
        height: Number(rectMatch[4]),
      };
      if (
        Number.isFinite(rectangle.x)
        && Number.isFinite(rectangle.y)
        && rectangle.width > 0
        && rectangle.height > 0
      ) {
        rectangles.push(rectangle);
      }
    }
    pages.push({
      width: Number(mediaBox[1]),
      height: Number(mediaBox[2]),
      rects: rectangles,
    });
  }
  return pages;
}

function vectorRows(page: PdfVectorPage): PdfVectorRow[] {
  const groups = new Map<string, PdfVectorRect[]>();
  for (const rectangle of page.rects) {
    const key = `${Math.round(rectangle.y * 100)}:${Math.round(rectangle.height * 100)}`;
    const group = groups.get(key) ?? [];
    group.push(rectangle);
    groups.set(key, group);
  }
  return [...groups.values()]
    .map((cells) => ({
      y: cells[0]!.y,
      height: cells[0]!.height,
      cells: cells.sort((left, right) => left.x - right.x),
    }))
    .sort((left, right) => left.y - right.y);
}

type PdfExpectedColumn = { key: string; label: string; kind: ReportValueKind };
type PdfExpectedPanel = {
  title: string;
  columns: PdfExpectedColumn[];
  rows: AnyRecord[];
  totalRow: AnyRecord | null;
};

function pdfExpectedKind(kind: string): ReportValueKind {
  return (["money", "quantity", "percentage", "count", "days"].includes(kind) ? kind : "text") as ReportValueKind;
}

function expectedPdfPanels(data: ComposedReport): PdfExpectedPanel[] {
  const tables: AnyRecord[] = [];
  if ((data.kpis as AnyRecord[]).length) {
    tables.push({
      id: "kpis",
      title: "",
      columns: [
        { key: "label", label: "Indicador", kind: "text" },
        { key: "value", label: "Valor", kind: "text" },
      ],
      rows: (data.kpis as AnyRecord[]).map((item) => ({
        label: item.label,
        value: formatReportValue(item.value, pdfExpectedKind(String(item.kind))),
      })),
      totals: {},
    });
  }
  if (Array.isArray(data.alerts) && data.alerts.length) {
    tables.push({
      id: "alerts",
      title: "",
      columns: [
        { key: "sesionId", label: "Sesión", kind: "count" },
        { key: "tipo", label: "Tipo", kind: "text" },
        { key: "mensaje", label: "Mensaje", kind: "text" },
        { key: "importe", label: "Importe", kind: "money" },
      ],
      rows: data.alerts.map((alert) => ({ ...alert })),
      totals: {},
    });
  }
  tables.push(
    ...normalizeExportTables(String(data.section), data.activeFilters, data.tables as ExportTable[]),
    ...(data.charts as AnyRecord[]).map((chart) => ({
      id: `chart-${chart.title}`,
      title: chart.title,
      columns: [
        { key: chart.categoryKey, label: labelForReportKey(String(chart.categoryKey)), kind: "text" },
        ...(chart.series ?? []).map((series: AnyRecord) => ({
          key: series.key,
          label: series.label,
          kind: series.kind ?? "text",
        })),
      ],
      rows: chart.rows ?? [],
      totals: {},
    })),
  );
  return tables.flatMap((table) => {
    const columns = table.columns as PdfExpectedColumn[];
    const panels = panelColumns(columns);
    const totalRow = hasMeaningfulTotals(table.totals)
      ? { ...(table.totals as AnyRecord) }
      : null;
    if (totalRow) {
      const label = reportTotalLabel(columns, totalRow);
      if (label && totalRow[label.key] == null) totalRow[label.key] = label.value;
    }
    return panels.map((panel, panelIndex) => ({
      title: table.title
        ? panels.length === 1
          ? String(table.title)
          : `${table.title} · Parte ${panelIndex + 1} de ${panels.length}`
        : "",
      columns: panel,
      rows: (table.rows ?? []) as AnyRecord[],
      totalRow,
    }));
  });
}

function pdfHeaderLabel(label: string): string {
  return label === "Part. %" ? "Participación" : label;
}

function headerCellKey(value: string): string {
  // pdftotext may split a long header at the glyph boundary (for example
  // "Reimpresione" + "s"). Compacting only the normalized header words
  // preserves exact cell/column matching while accepting that split.
  return geometryKey(value).replace(/\s+/g, "");
}

function cellWords(page: PdfBBoxPage, row: PdfVectorRow, cell: PdfVectorRect): PdfBBoxWord[] {
  return page.words
    .filter((word) => {
      const centerX = (word.xMin + word.xMax) / 2;
      const centerY = (word.yMin + word.yMax) / 2;
      return centerX >= cell.x - 0.01
        && centerX <= cell.x + cell.width + 0.01
        && centerY >= row.y - 0.01
        && centerY <= row.y + row.height + 0.01;
    })
    .sort((left, right) => left.yMin - right.yMin || left.xMin - right.xMin);
}

function headerRowMatches(
  page: PdfBBoxPage,
  row: PdfVectorRow,
  panel: PdfExpectedPanel,
): boolean {
  if (row.cells.length !== panel.columns.length) return false;
  const matched = row.cells.every((cell, index) => {
    const actual = headerCellKey(cellWords(page, row, cell).map((word) => word.text).join(" "));
    const expected = headerCellKey(pdfHeaderLabel(String(panel.columns[index]!.label)));
    return Boolean(expected) && actual === expected;
  });
  return matched;
}

function expectedPdfPanelRows(panel: PdfExpectedPanel): AnyRecord[] {
  const rows = [...panel.rows];
  if (panel.totalRow) rows.push(panel.totalRow);
  return rows;
}

function expectedPdfCellText(column: PdfExpectedColumn, row: AnyRecord): string {
  return formatReportValue(row[column.key], pdfExpectedKind(String(column.kind)));
}

function addTokenCounts(target: Map<string, number>, text: string): void {
  for (const token of geometryKey(text).split(" ").filter(Boolean)) {
    target.set(token, (target.get(token) ?? 0) + 1);
  }
}

function addCellTokenCounts(
  target: Map<string, number>,
  actualText: string,
  expectedText: string,
): void {
  // Independent bbox extraction separates a token when the renderer wraps it
  // at a line boundary (for example `ubicacionId` or the ISO millisecond
  // suffix). Recombine only contiguous fragments whose concatenation is
  // exactly the expected token; an omitted tail cannot satisfy this match.
  const actualTokens = phraseWords(actualText);
  const expectedTokens = phraseWords(expectedText);
  addTokenCounts(target, actualText);
  let actualCursor = 0;
  for (const expectedToken of expectedTokens) {
    while (actualCursor < actualTokens.length) {
      const current = actualTokens[actualCursor]!;
      if (current === expectedToken) {
        actualCursor += 1;
        break;
      }
      if (expectedToken.startsWith(current)) {
        let joined = current;
        let end = actualCursor;
        for (let candidate = actualCursor + 1; candidate < actualTokens.length; candidate += 1) {
          const combined = joined + actualTokens[candidate]!;
          if (!expectedToken.startsWith(combined)) break;
          joined = combined;
          end = candidate;
          if (joined === expectedToken) break;
        }
        if (joined === expectedToken && end > actualCursor) {
          for (let consumed = actualCursor; consumed <= end; consumed += 1) {
            const fragment = actualTokens[consumed]!;
            target.set(fragment, (target.get(fragment) ?? 0) - 1);
          }
          target.set(expectedToken, (target.get(expectedToken) ?? 0) + 1);
          actualCursor = end + 1;
          break;
        }
      }
      // Extra or mismatched text remains in the counts and is skipped only
      // for the positional search; it cannot satisfy a later expected token.
      actualCursor += 1;
    }
  }
  for (const [token, count] of [...target]) {
    if (count <= 0) target.delete(token);
  }
}

function pdfPanelGeometry(
  bytes: Buffer,
  data: ComposedReport,
): AnyRecord {
  // pdftotext reports glyph extents, while PDFKit cell rectangles use the
  // text baseline/line box. Keep the independent vector-cell check strict,
  // allowing only the documented font descent/antialiasing envelope.
  const textCellTolerance = 5;
  let pages: PdfBBoxPage[];
  let vectorPages: PdfVectorPage[];
  try {
    pages = parsePdfBBox(bytes);
    vectorPages = parsePdfVectorPages(bytes);
  } catch (error) {
    return {
      available: false,
      expectedPanels: 0,
      foundPanels: 0,
      headerChecks: 0,
      headerNotLocated: 0,
      headerOutOfBounds: 0,
      boundaryOutOfBounds: 0,
      vectorPageCount: 0,
      vectorRectCount: 0,
      vectorRowCount: 0,
      vectorCellWordChecks: 0,
      vectorWordOutOfBounds: 0,
      vectorUnassignedWords: 0,
      vectorRowErrors: 0,
      vectorRectOverlapCount: 0,
      columnOverlapCount: 0,
      errors: [error instanceof Error ? error.message.slice(0, 200) : "vector-geometry-unavailable"],
    };
  }
  const panels = expectedPdfPanels(data);
  const rowsByPage = vectorPages.map(vectorRows);
  const cellsByPage = vectorPages.map((page) => page.rects);
  let globalRowIndex = 0;
  const orderedRows = rowsByPage.flatMap((rows, pageIndex) =>
    rows.map((row, rowIndex) => ({
      pageIndex,
      rowIndex,
      row,
      globalRowIndex: globalRowIndex++,
    })),
  );
  let foundPanels = 0;
  let panelHeaderRowsFound = 0;
  let titleOutOfOrder = 0;
  let titleCursor = { pageIndex: -1, y: -Infinity };
  const usedHeaderRows = new Set<string>();
  let rowCursor = 0;
  const matchedPanels: Array<{
    panel: PdfExpectedPanel;
    globalRowIndex: number;
    pageIndex: number;
    rowIndex: number;
  }> = [];
  for (const panel of panels) {
    let header: typeof orderedRows[number] | undefined;
    if (panel.title) {
      const allOccurrences = findPhraseOccurrences(pages, panel.title);
      const occurrence = allOccurrences.find((candidate) => {
        const y = Math.min(...candidate.words.map((word) => word.yMin));
        return candidate.pageIndex > titleCursor.pageIndex
          || (candidate.pageIndex === titleCursor.pageIndex && y > titleCursor.y);
      });
      if (!occurrence) {
        if (allOccurrences.length) titleOutOfOrder += 1;
        continue;
      }
      const titleY = Math.min(...occurrence.words.map((word) => word.yMin));
      if (
        occurrence.pageIndex < titleCursor.pageIndex
        || (occurrence.pageIndex === titleCursor.pageIndex && titleY <= titleCursor.y)
      ) {
        titleOutOfOrder += 1;
      }
      titleCursor = { pageIndex: occurrence.pageIndex, y: titleY };
      header = orderedRows.find((candidate) =>
        candidate.globalRowIndex >= rowCursor
        && candidate.pageIndex === occurrence.pageIndex
        && candidate.row.y >= Math.max(...occurrence.words.map((word) => word.yMax)) - 0.5
        && !usedHeaderRows.has(`${candidate.pageIndex}:${candidate.rowIndex}`)
        && headerRowMatches(pages[candidate.pageIndex]!, candidate.row, panel),
      );
    } else {
      header = orderedRows.find((candidate) =>
        candidate.globalRowIndex >= rowCursor
        && !usedHeaderRows.has(`${candidate.pageIndex}:${candidate.rowIndex}`)
        && headerRowMatches(pages[candidate.pageIndex]!, candidate.row, panel),
      );
    }
    if (!header) continue;
    const headerKey = `${header.pageIndex}:${header.rowIndex}`;
    usedHeaderRows.add(headerKey);
    foundPanels += 1;
    panelHeaderRowsFound += 1;
    rowCursor = header.globalRowIndex + 1;
    matchedPanels.push({
      panel,
      globalRowIndex: header.globalRowIndex,
      pageIndex: header.pageIndex,
      rowIndex: header.rowIndex,
    });
  }
  let vectorRectCount = 0;
  let vectorRowCount = 0;
  let vectorRowErrors = 0;
  let vectorRectOverlapCount = 0;
  let vectorCellWordChecks = 0;
  let vectorWordOutOfBounds = 0;
  let vectorUnassignedWords = 0;
  let bodyRowsExpected = 0;
  let bodyRowsObserved = 0;
  let bodyRowDeficits = 0;
  let bodyRowShapeErrors = 0;
  let bodyCellsExpected = 0;
  let bodyCellsObserved = 0;
  let bodyTokensExpected = 0;
  let bodyTokensObserved = 0;
  let bodyTokenMissing = 0;
  const bodyTokenDeficits = new Map<string, number>();
  for (let panelIndex = 0; panelIndex < matchedPanels.length; panelIndex += 1) {
    const matched = matchedPanels[panelIndex]!;
    const next = matchedPanels[panelIndex + 1];
    const actualRows = orderedRows
      .slice(matched.globalRowIndex + 1, next?.globalRowIndex ?? orderedRows.length)
      .filter((candidate) =>
        !headerRowMatches(pages[candidate.pageIndex]!, candidate.row, matched.panel),
      );
    const expectedRows = expectedPdfPanelRows(matched.panel);
    bodyRowsExpected += expectedRows.length;
    bodyRowsObserved += actualRows.length;
    bodyRowDeficits += Math.max(0, expectedRows.length - actualRows.length);
    bodyCellsExpected += expectedRows.length * matched.panel.columns.length;
    for (const row of actualRows) {
      bodyCellsObserved += row.row.cells.length;
      if (row.row.cells.length !== matched.panel.columns.length) bodyRowShapeErrors += 1;
    }
    const expectedTokens = new Map<string, number>();
    const actualTokens = new Map<string, number>();
    for (const expectedRow of expectedRows) {
      for (const column of matched.panel.columns) {
        const text = expectedPdfCellText(column, expectedRow);
        const before = bodyTokensExpected;
        addTokenCounts(expectedTokens, text);
        bodyTokensExpected += geometryKey(text).split(" ").filter(Boolean).length;
        if (bodyTokensExpected < before) bodyTokensExpected = before;
      }
    }
    for (const [rowIndex, row] of actualRows.entries()) {
      const page = pages[row.pageIndex]!;
      for (const [cellIndex, cell] of row.row.cells.entries()) {
        const text = cellWords(page, row.row, cell).map((word) => word.text).join(" ");
        const expectedRow = expectedRows[rowIndex];
        const cellTokens = new Map<string, number>();
        const expectedColumn = matched.panel.columns[cellIndex];
        if (expectedRow && expectedColumn) {
          addCellTokenCounts(cellTokens, text, expectedPdfCellText(expectedColumn, expectedRow));
        } else {
          addTokenCounts(cellTokens, text);
        }
        for (const [token, count] of cellTokens) {
          actualTokens.set(token, (actualTokens.get(token) ?? 0) + count);
        }
        bodyTokensObserved += [...cellTokens.values()].reduce((sum, count) => sum + count, 0);
      }
    }
    for (const [token, expectedCount] of expectedTokens) {
      const missing = Math.max(0, expectedCount - (actualTokens.get(token) ?? 0));
      bodyTokenMissing += missing;
      if (missing) bodyTokenDeficits.set(token, (bodyTokenDeficits.get(token) ?? 0) + missing);
    }
  }
  for (let pageIndex = 0; pageIndex < vectorPages.length; pageIndex += 1) {
    const page = vectorPages[pageIndex]!;
    const rows = rowsByPage[pageIndex]!;
    vectorRectCount += page.rects.length;
    vectorRowCount += rows.length;
    for (const row of rows) {
      if (!row.cells.length) {
        vectorRowErrors += 1;
        continue;
      }
      let right = row.cells[0]!.x;
      for (const cell of row.cells) {
        if (
          cell.x < 33
          || cell.x + cell.width > page.width - 33
          || cell.y < 0
          || cell.y + cell.height > page.height
          || cell.height <= 0
        ) {
          vectorRowErrors += 1;
        }
        if (cell.x < right - 0.5) vectorRectOverlapCount += 1;
        if (Math.abs(cell.x - right) > 0.75) vectorRowErrors += 1;
        right = cell.x + cell.width;
      }
    }
    const cells = cellsByPage[pageIndex]!;
    const words = pages[pageIndex]?.words ?? [];
    for (const word of words) {
      const centerX = (word.xMin + word.xMax) / 2;
      const centerY = (word.yMin + word.yMax) / 2;
      const containing = cells.filter((cell) =>
        centerX >= cell.x - 0.01
        && centerX <= cell.x + cell.width + 0.01
        && centerY >= cell.y - 0.01
        && centerY <= cell.y + cell.height + 0.01,
      );
      if (containing.length > 1) vectorRectOverlapCount += containing.length - 1;
      if (containing.length === 1) {
        vectorCellWordChecks += 1;
        const cell = containing[0]!;
        if (
          word.xMin < cell.x - textCellTolerance
          || word.xMax > cell.x + cell.width + textCellTolerance
          || word.yMin < cell.y - textCellTolerance
          || word.yMax > cell.y + cell.height + textCellTolerance
        ) {
          vectorWordOutOfBounds += 1;
        }
      }
    }
    for (const row of rows) {
      const rowWords = words.filter((word) => {
        const centerY = (word.yMin + word.yMax) / 2;
        return centerY >= row.y - 0.01 && centerY <= row.y + row.height + 0.01;
      });
      for (const word of rowWords) {
        const centerX = (word.xMin + word.xMax) / 2;
        const centerY = (word.yMin + word.yMax) / 2;
        const inCell = cells.some((cell) =>
          centerX >= cell.x - 0.01
          && centerX <= cell.x + cell.width + 0.01
          && centerY >= cell.y - 0.01
          && centerY <= cell.y + cell.height + 0.01,
        );
        if (!inCell) vectorUnassignedWords += 1;
      }
    }
  }
  const expectedPanels = panels.length;
  const bodyCoverageOk = matchedPanels.length === panels.length
    && bodyRowDeficits === 0
    && bodyRowShapeErrors === 0
    && bodyTokenMissing === 0;
  const vectorOk = vectorPages.length === pages.length
    && vectorRectCount > 0
    && vectorRowCount > 0
    && panelHeaderRowsFound === expectedPanels
    && bodyCoverageOk
    && vectorRowErrors === 0
    && vectorRectOverlapCount === 0
    && vectorWordOutOfBounds === 0
    && vectorUnassignedWords === 0;
  return {
    available: true,
    pageCount: pages.length,
    expectedPanels,
    foundPanels,
    headerChecks: expectedPanels,
    headerNotLocated: expectedPanels - panelHeaderRowsFound,
    headerOutOfBounds: 0,
    boundaryOutOfBounds: 0,
    titleOutOfOrder,
    bodyRowsExpected,
    bodyRowsObserved,
    bodyRowDeficits,
    bodyRowShapeErrors,
    bodyCellsExpected,
    bodyCellsObserved,
    bodyTokensExpected,
    bodyTokensObserved,
    bodyTokenMissing,
    bodyTokenDiagnosticHash: hash(bodyTokenDeficits),
    vectorPageCount: vectorPages.length,
    vectorRectCount,
    vectorRowCount,
    vectorCellWordChecks,
    vectorWordOutOfBounds,
    vectorUnassignedWords,
    vectorRowErrors,
    vectorRectOverlapCount,
    columnOverlapCount: vectorRectOverlapCount,
    ok: expectedPanels === foundPanels && titleOutOfOrder === 0 && vectorOk,
  };
}

function panelColumns(columns: Array<{ key: string; label: string; kind: ReportValueKind }>) {
  if (columns.length <= 9) return [columns];
  const panels = [columns.slice(0, 6)];
  for (let start = 6; start < columns.length; start += 8) {
    panels.push([columns[0]!, ...columns.slice(start, start + 8)]);
  }
  return panels;
}

const CONTROL_LOGICAL_BLOCKS = [
  { key: "ajustes", tableId: "ajustes-inventario" },
  { key: "salidas-canceladas", tableId: "salidas-canceladas" },
  { key: "salidas-mas-24h", tableId: "salidas-vencidas" },
  { key: "abonos-incongruentes", tableId: "abonos-incongruentes" },
  { key: "tickets-cancelados", tableId: "cancelaciones-control" },
  { key: "reimpresiones", tableId: "reimpresiones-etiqueta" },
  // The cash source has two tables; this first table is its one logical marker.
  { key: "diferencias-caja", tableId: "diferencias-por-cajero" },
] as const;

type ControlBlockMarker = {
  key: string;
  siteId?: number;
  title: string | null;
};

function canonicalControlBlockTitles(
  data: ComposedReport,
  mode: CaseMode,
  comparisonSites: Array<{ id: number; label: string }>,
): ControlBlockMarker[] {
  const tables = data.tables as AnyRecord[];
  const sites = mode === "comparar"
    ? comparisonSites
    : [{ id: undefined, label: "" }];
  return sites.flatMap((site) =>
    CONTROL_LOGICAL_BLOCKS.map((block) => {
      const table = tables.find((candidate) =>
        String(candidate.id ?? "").replace(/^sitio-\d+-/, "") === block.tableId
        && (site.id === undefined || Number(candidate.siteId) === site.id)
        && typeof candidate.title === "string"
        && candidate.title.trim(),
      );
      return {
        key: block.key,
        ...(site.id === undefined ? {} : { siteId: site.id }),
        title: table ? String(table.title) : null,
      };
    }),
  );
}

function controlRawJsonCheck(
  bytes: Buffer,
  data: ComposedReport,
  mode: CaseMode,
  comparisonSites: Array<{ id: number; label: string }>,
): AnyRecord {
  let pages: PdfBBoxPage[];
  try {
    pages = parsePdfBBox(bytes);
  } catch {
    return {
      checkedBlocks: canonicalControlBlockTitles(data, mode, comparisonSites).length,
      blocksFound: 0,
      blocksWithContent: 0,
      blocksWithoutRawJson: 0,
      rawJsonHits: 0,
      available: false,
      ok: false,
    };
  }
  const blocks = canonicalControlBlockTitles(data, mode, comparisonSites);
  const markers: PdfPhraseOccurrence[] = [];
  let cursor = { pageIndex: -1, y: -Infinity };
  for (const block of blocks) {
    const marker = block.title
      ? findPhraseOccurrences(pages, block.title).find((occurrence) => {
      const y = Math.min(...occurrence.words.map((word) => word.yMin));
      return occurrence.pageIndex > cursor.pageIndex
        || (occurrence.pageIndex === cursor.pageIndex && y > cursor.y);
      })
      : undefined;
    if (marker) {
      markers.push(marker);
      cursor = {
        pageIndex: marker.pageIndex,
        y: Math.min(...marker.words.map((word) => word.yMin)),
      };
    }
  }
  const rawJsonPattern = /(?:\{\s*["']|["'](?:kpis|charts|tables|rows|columns|warnings|alerts)["']\s*:|\\["'])/gi;
  const fullText = pages.map(pageText).join("\n");
  const rawJsonHits = fullText.match(rawJsonPattern)?.length ?? 0;
  let blocksWithContent = 0;
  let blocksWithoutRawJson = 0;
  for (let index = 0; index < markers.length; index += 1) {
    const marker = markers[index]!;
    const next = markers[index + 1];
    const markerY = Math.min(...marker.words.map((word) => word.yMin));
    const nextY = next ? Math.min(...next.words.map((word) => word.yMin)) : Infinity;
    let blockText = "";
    for (let page = marker.pageIndex; page <= (next?.pageIndex ?? pages.length - 1); page += 1) {
      const words = pages[page]!.words;
      const eligible = words
        .filter((word) =>
          page !== marker.pageIndex || word.yMin >= markerY - 1,
        )
        .filter((word) =>
          !next || page !== next.pageIndex || word.yMin < nextY - 1,
        );
      blockText += eligible.map((word) => word.text).join(" ");
      blockText += "\n";
    }
    if (blockText.trim()) {
      blocksWithContent += 1;
      if (!(blockText.match(rawJsonPattern)?.length ?? 0)) blocksWithoutRawJson += 1;
    }
  }
  return {
    checkedBlocks: blocks.length,
    blocksFound: markers.length,
    blocksWithContent,
    blocksWithoutRawJson,
    rawJsonHits,
    available: true,
    ok: markers.length === blocks.length
      && blocksWithContent === blocks.length
      && blocksWithoutRawJson === blocks.length
      && rawJsonHits === 0,
    dataShapeUsed: {
      tables: (data.tables as AnyRecord[]).length,
      charts: (data.charts as AnyRecord[]).length,
    },
  };
}

function renderRepresentativePages(
  bytes: Buffer,
  pdfPath: string,
  text: string,
  outputPrefix: string,
  actualPageCount: number,
): string[] {
  const pages = text.split("\f");
  const x04Page = pages.findIndex((page) => page.includes("X04"));
  const widePage = pages.findIndex((page) => /Parte [2-9] de [2-9]/.test(page));
  const pageCount = Math.max(1, actualPageCount || pages.length);
  const pageNumbers = [...new Set([
    1,
    widePage >= 0 ? widePage + 1 : 1,
    x04Page >= 0 ? x04Page + 1 : 1,
    pageCount,
  ])];
  writeFileSync(pdfPath, bytes, { mode: 0o600 });
  const paths: string[] = [];
  for (const page of pageNumbers) {
    const outputBase = `${outputPrefix}-page-${page}`;
    try {
      execFileSync("pdftoppm", [
        "-f", String(page), "-l", String(page), "-singlefile", "-png", "-r", "120",
        pdfPath, outputBase,
      ], { stdio: ["ignore", "ignore", "ignore"] });
      const outputPath = `${outputBase}.png`;
      paths.push(outputPath);
      chmodSync(outputPath, 0o600);
    } catch {
      // pdfMetrics already records independent rendering availability.
    }
  }
  return paths;
}

function pdfTableChecks(text: string, data: ComposedReport): {
  ok: boolean;
  missing: string[];
  tableCount: number;
  headerCount: number;
  totalCount: number;
  valueChecks: number;
} {
  const comparable = (value: unknown) => String(value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .toLowerCase();
  const normalized = comparable(text);
  const tables = [
    ...normalizeExportTables(String(data.section), data.activeFilters, data.tables as ExportTable[]),
    ...(data.charts as AnyRecord[]).map((chart) => ({
      id: `chart-${chart.title}`,
      title: chart.title,
      columns: [
        { key: chart.categoryKey, label: labelForReportKey(String(chart.categoryKey)), kind: "text" },
        ...(chart.series ?? []).map((series: AnyRecord) => ({
          key: series.key,
          label: series.label,
          kind: series.kind ?? "text",
        })),
      ],
      rows: chart.rows ?? [],
      totals: {},
    })),
  ];
  const missing: string[] = [];
  let headerCount = 0;
  let totalCount = 0;
  let valueChecks = 0;
  const numericKinds = new Set(["money", "quantity", "percentage", "count", "days"]);
  const visibleValue = (column: { kind: string }, value: unknown) => formatReportValue(
    value,
    numericKinds.has(column.kind)
      ? column.kind as "money" | "quantity" | "percentage" | "count" | "days"
      : "text",
  );
  const checkRowValues = (
    table: { id: string; columns: Array<{ key: string; kind: string }>; rows: Record<string, unknown>[] },
    row: Record<string, unknown>,
    suffix: string,
  ) => {
    const identifierKey = table.columns.find((column) => column.kind === "text")?.key;
    for (const column of table.columns) {
      if (
        !numericKinds.has(column.kind) &&
        (column.key !== identifierKey || typeof row[column.key] !== "string")
      ) continue;
      const value = visibleValue(column, row[column.key]);
      // Long evidence URLs/messages are independently covered by geometry and
      // wrapping checks; numeric cells and compact identifiers must be visible.
      if (value.length > 160 && !numericKinds.has(column.kind)) continue;
      valueChecks += 1;
      if (!normalized.includes(comparable(value))) missing.push(`${table.id}.value:${suffix}:${column.key}`);
    }
  };
  for (const kpi of data.kpis as AnyRecord[]) {
    valueChecks += 1;
    if (!normalized.includes(comparable(String(kpi.label)))) missing.push(`kpi.label:${String(kpi.id ?? kpi.label)}`);
    const value = formatReportValue(
      kpi.value,
      numericKinds.has(String(kpi.kind))
        ? String(kpi.kind) as "money" | "quantity" | "percentage" | "count" | "days"
        : "text",
    );
    if (!normalized.includes(comparable(value))) missing.push(`kpi.value:${String(kpi.id ?? kpi.label)}`);
  }
  for (const table of tables) {
    const title = comparable(table.title);
    if (!normalized.includes(title)) {
      missing.push(String(table.id));
      continue;
    }
    headerCount += 1;
    for (const column of table.columns) {
      const label = column.label === "Part. %" ? "Participación" : column.label;
      if (!normalized.includes(comparable(label))) missing.push(`${table.id}.header:${label}`);
    }
    const representativeRows = table.rows.length === 1
      ? [table.rows[0]!]
      : [table.rows[0]!, table.rows.at(-1)!];
    representativeRows.forEach((row, index) => {
      if (row) checkRowValues(table, row, index === 0 ? "first" : "last");
    });
    if (hasMeaningfulTotals(table.totals)) {
      totalCount += 1;
      const totalLabel = reportTotalLabel(table.columns, table.totals);
      if (totalLabel && !normalized.includes(comparable(totalLabel.value))) {
        missing.push(`${table.id}.total-row`);
      }
      checkRowValues({ ...table, rows: [table.totals] }, table.totals, "total");
    }
  }
  const forbidden = [
    "previousdesde", "previoushasta", "yearagodesde", "yearagohasta",
    "ubicacionids=", "productoids=", "usuarioids=", "clienteids=", "proveedorids=",
    "totales:", "\"rows\"", "\"columns\"",
  ];
  for (const key of forbidden) if (normalized.includes(key)) missing.push(`forbidden:${key}`);
  if (text.includes("\uFFFD")) missing.push("unicode-replacement-character");
  // These are the stable labels that proved the old ASCII PDF fallback was
  // replacing Unicode glyphs; ordinary business punctuation may be a question
  // mark and must not create a false failure.
  if (/[Pp]\?gina|D\?a|Participaci\?n|M\?xico/.test(text)) missing.push("ascii-substitution");
  if (!text.includes("Página") || !text.includes("→")) missing.push("unicode-page-marker");
  const expectsDiaLabel = tables.some((table) =>
    table.columns.some((column) => /día/i.test(column.label)),
  );
  const expectsParticipationLabel = tables.some((table) =>
    table.columns.some((column) => /participación|part\. %/i.test(column.label)),
  );
  if (expectsDiaLabel && !text.includes("Día")) missing.push("unicode-dia-label");
  if (expectsParticipationLabel && !text.includes("Participación")) missing.push("unicode-participation-label");
  return {
    ok: missing.length === 0,
    missing,
    tableCount: tables.length,
    headerCount,
    totalCount,
    valueChecks,
  };
}

function equalValues(left: unknown, right: unknown): boolean {
  return stable(left) === stable(right);
}

type RequestHarness = {
  baseUrl: string;
  setAuth(mode: AuthMode): void;
  get(path: string, expectedContent?: "json" | "xlsx" | "pdf"): Promise<{ status: number; bytes: Buffer; json?: AnyRecord; contentType: string }>;
  close(): Promise<void>;
};

async function makeHarness(): Promise<RequestHarness> {
  const [{ default: reportesRouter }, { default: analyticsRouter }] = await Promise.all([
    import("../routes/reportes"),
    import("../routes/admin-analytics"),
  ]);
  const authFor = (mode: AuthMode): AnyRecord => ({
    sessionId: "read-only-export-verification",
    user: {
      id: mode === "admin" ? 0 : -1,
      nombre: "verification-only",
      usuario: "verification-only",
      rol: mode === "admin" ? "ADMIN" : "CAJA",
      alcanceConsulta: mode === "admin" ? "TODAS" : "PROPIA",
      ubicacionId: mode === "admin" ? null : 1,
      activo: true,
    },
    location: null,
  });
  const patchSessionOnly = (router: any, preserve?: any) => {
    for (const layer of router.stack ?? []) {
      if (layer.route || layer.handle === preserve) continue;
      if (layer.handle?.name === "requireSession") {
        layer.handle = (_req: any, _res: any, next: any) => next();
      }
    }
  };
  // Keep every requireRole layer. Only session lookup is bypassed. Reportes'
  // permission layer is intentionally replaced because this harness has no
  // persisted user/permission/session state; the ADMIN Control role gate is
  // the actual imported function and remains untouched.
  patchSessionOnly(reportesRouter, controlOperativoRoleGate);
  patchSessionOnly(analyticsRouter);
  for (const layer of (reportesRouter as any).stack ?? []) {
    if (!layer.route && layer.handle !== controlOperativoRoleGate && layer.handle?.name !== "requireSession") {
      layer.handle = (_req: any, _res: any, next: any) => next();
    }
  }
  const app: Express = express();
  let activeAuth = authFor("admin");
  app.use((req, _res, next) => {
    req.auth = activeAuth as any;
    next();
  });
  app.use(express.json());
  app.use("/api", reportesRouter);
  app.use("/api", analyticsRouter);
  app.use((error: unknown, _req: any, res: any, _next: any) => {
    res.status(500).json({ error: "Harness route failure", kind: error instanceof Error ? error.name : "unknown" });
  });
  const server = createServer(app);
  await new Promise<void>((resolveListen, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => resolveListen());
  });
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("No se pudo abrir el arnés HTTP local.");
  const baseUrl = `http://127.0.0.1:${address.port}`;
  return {
    baseUrl,
    setAuth(mode) { activeAuth = authFor(mode); },
    async get(path, expectedContent) {
      const response = await fetch(`${baseUrl}${path}`);
      const bytes = Buffer.from(await response.arrayBuffer());
      const contentType = response.headers.get("content-type") ?? "";
      if (expectedContent && response.status === 200 && !contentType.includes(expectedContent === "xlsx"
        ? "spreadsheet"
        : expectedContent)) {
        throw new Error(`Tipo inesperado en ${path}: ${contentType}`);
      }
      let json: AnyRecord | undefined;
      if (contentType.includes("json") && bytes.length) json = JSON.parse(bytes.toString("utf8"));
      return { status: response.status, bytes, json, contentType };
    },
    async close() {
      await new Promise<void>((resolveClose, reject) => server.close((error) => error ? reject(error) : resolveClose()));
    },
  };
}

async function withReadOnlySnapshot<T>(callback: (query: (text: string, values?: unknown[]) => Promise<any>) => Promise<T>): Promise<T> {
  const client = await (pool as any).connect();
  let pending: Promise<unknown> = Promise.resolve();
  const originalQuery = (pool as any).query;
  const originalConnect = (pool as any).connect;
  const originalClientQuery = client.query.bind(client);
  const query = (text: string | AnyRecord, values: unknown[] = []) => {
    const sql = typeof text === "string" ? text : text.text;
    const params = typeof text === "string" ? values : text.values ?? values;
    if (WRITE_SQL.test(sql)) throw new Error("La verificación rechazó una sentencia que no es de lectura.");
    const operation = pending.then(async () => {
      if (typeof text === "string") return originalClientQuery(sql, params);
      return originalClientQuery({ ...text, values: params });
    });
    pending = operation.then(() => undefined, () => undefined);
    return operation;
  };
  await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");
  try {
    (pool as any).query = query;
    (pool as any).connect = async () => {
      const readonlyClient = Object.create(client);
      readonlyClient.query = query;
      readonlyClient.release = () => undefined;
      return readonlyClient;
    };
    return await callback((text, values) => query(text, values));
  } finally {
    await pending;
    await client.query("ROLLBACK").catch(() => undefined);
    (pool as any).query = originalQuery;
    (pool as any).connect = originalConnect;
    client.release();
    await (pool as any).end();
  }
}

async function discoverYear(query: (text: string, values?: unknown[]) => Promise<any>): Promise<{ year: number; sites: number[] }> {
  const eventAt = accountedDocumentAt("t");
  const predicate = accountedDocumentPredicate("t");
  const years = await query(
    `SELECT EXTRACT(YEAR FROM (${eventAt} AT TIME ZONE 'America/Mexico_City'))::int AS year,
            COUNT(DISTINCT t.id)::int AS tickets
       FROM tickets t WHERE ${predicate} AND ${eventAt} IS NOT NULL
       GROUP BY 1 ORDER BY tickets DESC,year DESC`,
  );
  const candidates = [2026, ...years.rows.map((row: AnyRecord) => Number(row.year))].filter((year, index, all) =>
    Number.isInteger(year) && all.indexOf(year) === index,
  );
  for (const year of candidates) {
    const result = await query(
      `SELECT t.ubicacion_id::int AS site_id,COUNT(DISTINCT t.id)::int AS tickets,
              COALESCE(SUM(l.importe),0)::numeric AS sales
         FROM tickets t JOIN ticket_lineas l ON l.ticket_id=t.id
        WHERE ${predicate} AND ${eventAt} >= $1::timestamptz AND ${eventAt} < $2::timestamptz
        GROUP BY t.ubicacion_id HAVING COUNT(DISTINCT t.id)>0
        ORDER BY sales DESC,tickets DESC,site_id`,
      [`${year}-01-01T00:00:00.000Z`, `${year + 1}-01-01T00:00:00.000Z`],
    );
    const sites = result.rows
      .map((row: AnyRecord) => ({ id: Number(row.site_id), sales: Number(row.sales) }))
      .filter((row: AnyRecord) => Number.isInteger(row.id) && row.sales > 0)
      .map((row: AnyRecord) => row.id);
    if (sites.length >= 2) return { year, sites };
  }
  throw new Error("No se encontraron dos sitios reales con ventas cobradas/autorizadas.");
}

async function discoverComparisonSites(
  query: (text: string, values?: unknown[]) => Promise<any>,
): Promise<Array<{ id: number; label: string }>> {
  const result = await query(
    `SELECT id::int AS id,nombre
       FROM ubicaciones
      WHERE activa=true AND tipo IN ('TIENDA','BODEGA')
      ORDER BY nombre,id`,
  );
  return result.rows
    .map((row: AnyRecord) => ({ id: Number(row.id), label: String(row.nombre) }))
    .filter((site: { id: number; label: string }) => Number.isInteger(site.id) && site.label.length > 0);
}

async function requestJson(harness: RequestHarness, path: string): Promise<AnyRecord> {
  const response = await harness.get(path, "json");
  if (response.status !== 200 || !response.json) {
    const error = response.json?.error;
    throw new Error(`JSON ${response.status} en ${path}${error ? `: ${String(error).slice(0, 300)}` : ""}`);
  }
  return response.json;
}

async function screenContent(
  harness: RequestHarness,
  view: View,
  base: AnyRecord,
  mode: CaseMode,
  comparisonSites: Array<{ id: number; label: string }>,
): Promise<{ content: Content; coverage: AnyRecord[] }> {
  const coverage: AnyRecord[] = [];
  const frameIds = mode === "comparar" ? comparisonSites.map((site) => site.id) : [undefined];
  const frameContents: Content[] = [];
  for (let index = 0; index < frameIds.length; index += 1) {
    const siteId = frameIds[index];
    const sourceContents: Content[] = [];
    for (const source of REPORT_SOURCES[view]) {
      const response = await requestJson(harness, `/api/reportes/${source}?${routeQuery(sourceQuery(base, siteId))}`);
      const content = asContent(response);
      sourceContents.push(content);
      coverage.push({ frame: mode === "comparar" ? index + 1 : 0, source, ...sourceCoverage(content) });
    }
    if (view === "control-operativo") {
      const cashPath = `/api/admin/diferencias?${routeQuery({
        desde: base.desde, hasta: base.hasta,
        ...(siteId === undefined ? {} : { ubicacionId: siteId }),
        umbralCorte: 0, umbralTienda: 0, agrupacion: "semana",
      })}`;
      const cash = await requestJson(harness, cashPath);
      const content = cashContent(cash, base, siteId);
      sourceContents.push(content);
      coverage.push({ frame: mode === "comparar" ? index + 1 : 0, source: "diferencias-caja", ...sourceCoverage(content) });
    }
    frameContents.push(mode === "comparar"
      ? decorate(appendContent(sourceContents), index, comparisonSites[index]!)
      : appendContent(sourceContents));
  }
  let content = appendContent(frameContents);
  if (view === "ventas" && (mode === "normal" || mode === "comparar")) {
    const globalPath = `/api/admin/comparacion-tiendas?${routeQuery({
      periodo: "personalizado", desde: base.desde, hasta: base.hasta,
    })}`;
    const x04 = await requestJson(harness, globalPath);
    const normalizedX04 = normalizeComparisonPayload(x04);
    const x04Content: Content = {
      kpis: [],
      charts: comparisonCharts(normalizedX04 as any),
      tables: [comparisonTable(normalizedX04 as any)],
      warnings: [],
    };
    content = appendContent([content, x04Content]);
    coverage.push({ frame: 0, source: "admin/comparacion-tiendas", ...sourceCoverage(x04Content) });
  }
  return { content, coverage };
}

async function verifyCase(
  harness: RequestHarness,
  view: View,
  mode: CaseMode,
  base: AnyRecord,
  comparisonSites: Array<{ id: number; label: string }>,
  writeArtifacts: boolean,
): Promise<AnyRecord> {
  const input: ComposedReportInput = exportQuery(base, mode) as ComposedReportInput;
  const locations = undefined;
  const direct = await buildComposedReport(view, input, locations, true, {
    rol: "ADMIN",
    alcanceConsulta: "TODAS",
  });
  const directRecord = direct as AnyRecord;
  const screen = await screenContent(harness, view, base, mode, comparisonSites);
  const comparableTables = (tables: unknown) =>
    (Array.isArray(tables) ? tables : []).map((table: AnyRecord) => {
      const { economic: _economic, ...withoutEconomicMarker } = table;
      return withoutEconomicMarker;
    });
  const screenComparable = {
    kpis: screen.content.kpis,
    charts: screen.content.charts,
    tables: comparableTables(screen.content.tables),
    warnings: screen.content.warnings,
    alerts: screen.content.alerts ?? [],
  };
  const directComparable = {
    kpis: directRecord.kpis,
    charts: directRecord.charts,
    tables: comparableTables(directRecord.tables),
    warnings: directRecord.warnings,
    alerts: directRecord.alerts ?? [],
  };
  const screenMatchesBuilder = equalValues(screenComparable, directComparable);
  if (!screenMatchesBuilder) {
    const blockSummary = (value: AnyRecord) => ({
      kpiCount: (value.kpis ?? []).length,
      chartCount: (value.charts ?? []).length,
      tableCount: (value.tables ?? []).length,
      chartIdsHash: hash((value.charts ?? []).map((item: AnyRecord) => String(item.id))),
      tableIdsHash: hash((value.tables ?? []).map((item: AnyRecord) => String(item.id))),
      rowCountsHash: hash((value.tables ?? []).map((item: AnyRecord) => Array.isArray(item.rows) ? item.rows.length : 0)),
      kpisByFrame: Object.fromEntries((value.kpis ?? []).reduce((counts: Map<string, number>, item: AnyRecord) => {
        const frame = String(item.id).split("-").slice(0, 2).join("-");
        counts.set(frame, (counts.get(frame) ?? 0) + 1);
        return counts;
      }, new Map<string, number>())),
      warnings: Array.isArray(value.warnings) ? value.warnings.length : 0,
      alerts: Array.isArray(value.alerts) ? value.alerts.length : 0,
    });
    const mismatchedBlocks = (left: AnyRecord, right: AnyRecord, key: "kpis" | "charts" | "tables") => {
      const leftItems = left[key] ?? [];
      const rightItems = right[key] ?? [];
      return leftItems.flatMap((item: AnyRecord, index: number) => {
        const other = rightItems[index];
        return other && hash(item) === hash(other)
          ? []
          : [`${String(item.id)}:${hash(item)}!=${other ? hash(other) : "missing"}`];
      }).slice(0, 12);
    };
    throw new Error(
      `La composición de pantalla no coincide con el builder en ${view}/${mode}. `
      + `screen=${hash(screenComparable)} builder=${hash(directComparable)} `
      + `screenShape=${JSON.stringify(blockSummary(screenComparable))} `
      + `builderShape=${JSON.stringify(blockSummary(directComparable))} `
      + `blockDiff=${JSON.stringify({
        kpis: mismatchedBlocks(screenComparable, directComparable, "kpis"),
        charts: mismatchedBlocks(screenComparable, directComparable, "charts"),
        tables: mismatchedBlocks(screenComparable, directComparable, "tables"),
      })} warningDiff=${JSON.stringify({
        screenCount: screenComparable.warnings?.length ?? 0,
        builderCount: directComparable.warnings?.length ?? 0,
        screenHash: hash(screenComparable.warnings),
        builderHash: hash(directComparable.warnings),
      })}`,
    );
  }
  const xlsxPath = `/api/reportes/vistas/${view}/export.xlsx?${routeQuery(input)}`;
  const pdfPath = `/api/reportes/vistas/${view}/export.pdf?${routeQuery(input)}`;
  const xlsx = await harness.get(xlsxPath, "xlsx");
  const pdf = await harness.get(pdfPath, "pdf");
  if (xlsx.status !== 200 || pdf.status !== 200) throw new Error(`Descarga HTTP fallida en ${view}/${mode}.`);
  const workbook = await inspectWorkbook(xlsx.bytes, direct);
  const actualPdfHash = bytesHash(pdf.bytes);
  const pdfInspect = pdfMetrics(pdf.bytes);
  const { text: privatePdfText, ...pdfSummary } = pdfInspect;
  const pdfTextCheck = privatePdfText
    ? pdfTableChecks(privatePdfText, direct)
    : {
      ok: false,
      missing: ["no-independent-pdf-text"],
      tableCount: 0,
      headerCount: 0,
      totalCount: 0,
      valueChecks: 0,
    };
  const panelGeometry = pdfPanelGeometry(pdf.bytes, direct);
  const controlJson = view === "control-operativo"
    ? controlRawJsonCheck(pdf.bytes, direct, mode, comparisonSites)
    : null;
  const parsedOk = workbook.validZip
    && workbook.mismatches.length === 0
    && pdfTextCheck.ok
    && pdfTextCheck.tableCount === (direct.tables as AnyRecord[]).length + (direct.charts as AnyRecord[]).length
    && pdfTextCheck.headerCount === pdfTextCheck.tableCount
    && (!pdfSummary.fitz || pdfSummary.renderedPages > 0)
    && (panelGeometry.available === true
      && panelGeometry.ok === true
      && (!controlJson || controlJson.ok === true));
  if (!parsedOk) {
    throw new Error(
      `Contenido exportado incompleto en ${view}/${mode}. `
      + `xlsx=${JSON.stringify(workbook)} `
      + `pdf=${JSON.stringify({
        actualHash: actualPdfHash,
        textCheck: pdfTextCheck,
        panelGeometry,
        controlJson,
        actual: pdfSummary,
      })}`,
    );
  }
  let artifactPaths: AnyRecord | undefined;
  if (writeArtifacts) {
    const artifactStem = view === "ventas" && mode === "normal"
      ? "reportes-ventas-normal-global"
      : view === "que-comprar" && mode === "normal"
        ? "reportes-que-comprar-normal"
        : `reportes-${view}-${mode}`;
    const xlsxArtifact = join(EXPORT_DIR, `${artifactStem}.xlsx`);
    const pdfArtifact = join(EXPORT_DIR, `${artifactStem}.pdf`);
    await mkdir(EXPORT_DIR, { recursive: true, mode: 0o700 });
    for (const name of readdirSync(EXPORT_DIR)) {
      if (name.startsWith(`${artifactStem}-page-`) && name.endsWith(".png")) {
        await rm(join(EXPORT_DIR, name), { force: true });
      }
    }
    await writeFile(xlsxArtifact, xlsx.bytes, { mode: 0o600 });
    await writeFile(pdfArtifact, pdf.bytes, { mode: 0o600 });
    await chmod(xlsxArtifact, 0o600);
    await chmod(pdfArtifact, 0o600);
    const representativePages = renderRepresentativePages(
      pdf.bytes,
      pdfArtifact,
      privatePdfText ?? "",
      join(EXPORT_DIR, artifactStem),
      Number(pdfSummary.pageCount),
    );
    artifactPaths = {
      xlsx: `reports/exports/${artifactStem}.xlsx`,
      pdf: `reports/exports/${artifactStem}.pdf`,
      representativePages: representativePages.map((path) => path.replace(
        `${resolve(fileURLToPath(import.meta.url), "../../../../..")}/`,
        "",
      )),
    };
  }
  return {
    view,
    mode,
    sourceCoverage: screen.coverage,
    composed: {
      kpis: directRecord.kpis.length,
      charts: directRecord.charts.length,
      tables: directRecord.tables.length,
      rows: (directRecord.tables as AnyRecord[]).reduce((sum, table) => sum + table.rows.length, 0),
      totals: (directRecord.tables as AnyRecord[]).filter((table) => table.totals).length,
      contentHash: hash(directComparable),
    },
    downloads: {
      xlsx: {
        status: xlsx.status,
        contentType: xlsx.contentType,
        bytes: xlsx.bytes.length,
        sha256: bytesHash(xlsx.bytes),
        ...workbook,
      },
      pdf: {
        status: pdf.status,
        contentType: pdf.contentType,
        bytes: pdf.bytes.length,
        sha256: actualPdfHash,
        tableChecks: pdfTextCheck,
        ...pdfSummary,
      },
    },
    screenMatchesBuilder,
      pdfGeometry: panelGeometry,
      controlRawJson: controlJson,
    artifacts: artifactPaths ?? null,
      status: "PASS",
  };
}

async function assertControlRoleMatrix(harness: RequestHarness, base: AnyRecord): Promise<AnyRecord> {
  const query = routeQuery(exportQuery(base, "normal"));
  const paths = [
    `/api/reportes/control-operativo/export.xlsx?${query}`,
    `/api/reportes/control-operativo/export.pdf?${query}`,
    `/api/reportes/vistas/control-operativo/export.xlsx?${query}`,
    `/api/reportes/vistas/control-operativo/export.pdf?${query}`,
  ];
  harness.setAuth("nonadmin");
  const nonAdmin = [];
  for (const path of paths) nonAdmin.push((await harness.get(path)).status);
  harness.setAuth("admin");
  const admin = [];
  for (const path of paths) admin.push((await harness.get(path)).status);
  if (nonAdmin.some((status) => status !== 403) || admin.some((status) => status !== 200)) {
    throw new Error("La matriz HTTP de role gate para exportaciones Control no coincide.");
  }
  return { paths: paths.map((path) => path.replace(/\?.*$/, "")), nonAdmin, admin };
}

function safeError(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  const category = message.includes("Contenido exportado incompleto")
    ? "export-content-or-geometry-criterion"
    : message.includes("role gate")
      ? "control-role-matrix-criterion"
      : "readonly-harness-criterion";
  const diagnosticHash = createHash("sha256").update(message).digest("hex");
  return `${category}; diagnosticHash=${diagnosticHash}`;
}

function historicalEvidence(): string[] {
  try {
    const baseline = execFileSync("git", ["show", "HEAD:reports/export-download-verification.md"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return baseline
      .split("\n")
      .filter((line) => /^\| (ventas|que-comprar) \| normal \|/.test(line))
      .slice(0, 2);
  } catch {
    return [];
  }
}

async function writeReport(report: AnyRecord): Promise<void> {
  const cases = Array.isArray(report.cases) ? report.cases : [];
  const controlCompare = cases.find((item: AnyRecord) =>
    item.view === "control-operativo" && item.mode === "comparar" && item.status === "PASS");
  const priorEvidence = Array.isArray(report.priorEvidence) ? report.priorEvidence : [];
  const lines = [
    "# Verificación de descargas XLSX/PDF de Reportes (solo lectura)",
    "",
    `Estado: **${report.status}**.`,
    "",
    "## Alcance y limitación",
    "",
    "Se montaron los routers reales en un arnés Express local sobre `127.0.0.1`.",
    "No es una descarga contra la aplicación desplegada, no es un navegador y no crea una sesión real:",
    "el arnés inyecta un contexto autorizado en memoria. La comprobación sí invoca los handlers HTTP",
    "reales y recibe sus bytes. El contexto ADMIN se usó para cubrir las cinco pestañas y el comparativo;",
    "la matriz de Control conserva el middleware de rol real y verifica ADMIN/non-ADMIN.",
    "",
    "Todas las lecturas, incluidas las hechas por rutas y comparativos, usaron una única conexión",
    "`READ ONLY REPEATABLE READ`. Se rechazaron sentencias de escritura. No se ejecutaron inicializadores,",
    "usuarios, sesiones, fixtures ni escrituras de negocio. El reporte no contiene filas ni nombres privados.",
    "",
    "## Fuentes de pantalla cubiertas",
    "",
    "La composición se comparó contra las respuestas JSON de cada fuente que consume la pantalla:",
    "`Ventas`, `Qué comprar` (`que-comprar`, `inventario`, `mapas-calor`, `color`, `compras`),",
    "`Utilidad`, `Clientes` (`clientes`, `pagos-dirigidos`) y `Control operativo`",
    "(`control-operativo` más `admin/diferencias`). Ventas global incluye también X04",
    "(`admin/comparacion-tiendas`), tanto en Normal como en Comparar.",
    "",
    "## Resultados",
    "",
    `- Snapshot: \`${report.snapshot}\``,
    `- Periodo real seleccionado: \`${report.period}\``,
    `- Sitios elegibles para marcos de comparación: ${report.comparisonSiteCount}`,
    `- Casos verificados: ${cases.length}`,
    `- Errores: ${report.errors.length}`,
    "",
    "| Vista | Modo | Estado | Fuentes (KPI/chart/tabla/filas) | XLSX bytes / SHA-256 | PDF bytes / SHA-256 | PDF lectura + geometría | Pantalla=builder |",
    "|---|---|---|---|---:|---|---|---|",
    ...cases.map((item: AnyRecord) => {
      if (item.status !== "PASS") {
        return `| ${item.view} | ${item.mode} | **FAILED** | — | — | — | ${String(item.error ?? "fallo no especificado")} | false |`;
      }
      const sourceSummary = item.sourceCoverage
        .map((source: AnyRecord) => `${source.source} ${source.kpis}/${source.charts}/${source.tables}/${source.rows}`)
        .join("; ");
      const pdfCheck = item.downloads.pdf.tableChecks;
      const geometry = item.pdfGeometry;
      const controlJson = item.controlRawJson;
      const geometrySummary = [
        `${pdfCheck.tableCount} tablas, ${pdfCheck.headerCount} encabezados, ${pdfCheck.totalCount} totales, ${pdfCheck.valueChecks} valores`,
        `paneles ${geometry.foundPanels}/${geometry.expectedPanels}`,
        `páginas vector ${geometry.vectorPageCount}/${geometry.pageCount}, rectángulos ${geometry.vectorRectCount}, filas ${geometry.vectorRowCount}`,
        `palabras en celdas ${geometry.vectorCellWordChecks}, fuera ${geometry.vectorWordOutOfBounds}, sin asignar ${geometry.vectorUnassignedWords}`,
        `errores de fila ${geometry.vectorRowErrors}, solapes de celdas ${geometry.vectorRectOverlapCount}`,
        `cobertura cuerpo ${geometry.bodyRowsObserved}/${geometry.bodyRowsExpected} filas, ${geometry.bodyTokensObserved}/${geometry.bodyTokensExpected} tokens, faltan ${geometry.bodyTokenMissing}`,
        controlJson
          ? `Control bloques ${controlJson.blocksWithoutRawJson}/${controlJson.checkedBlocks} sin JSON; con contenido ${controlJson.blocksWithContent}/${controlJson.checkedBlocks}`
          : null,
      ].filter(Boolean).join("; ");
      return `| ${item.view} | ${item.mode} | **PASS** | ${sourceSummary} | ${item.downloads.xlsx.bytes} / \`${item.downloads.xlsx.sha256}\` | ${item.downloads.pdf.bytes} / \`${item.downloads.pdf.sha256}\` | ${geometrySummary} | ${String(item.screenMatchesBuilder)} |`;
    }),
    "",
    controlCompare
      ? `Control Comparar: ${controlCompare.controlRawJson.checkedBlocks} bloques de sitio comprobados; ${controlCompare.controlRawJson.blocksWithoutRawJson} sin JSON crudo; coincidencias JSON: ${controlCompare.controlRawJson.rawJsonHits}.`
      : "Control Comparar: no quedó un caso PASS del comparativo para comprobar sus siete bloques.",
    "En cada caso se asociaron títulos en orden único y se extrajeron rectángulos vectoriales reales",
    "de cada página del PDF; cada panel consume una fila de encabezado única con el conteo exacto",
    "de columnas y todas sus etiquetas dentro de la celda correspondiente.",
    "Las coordenadas no se reconstruyeron con anchos del renderer: se leyeron de los streams vectoriales",
    "independientes y se rechazaron filas con huecos, celdas solapadas, texto fuera o palabras sin celda.",
    "La comparación de texto contra rectángulos permite únicamente 5 pt de descenso tipográfico",
    "documentado entre el bbox independiente y el rectángulo vectorial; no se relaja la geometría de celdas.",
    "La cobertura del cuerpo exige todas las filas esperadas, forma de celdas y multiplicidad de tokens",
    "de cada valor proyectado por panel, incluyendo columnas de identidad repetidas y filas envueltas.",
    "Los hashes de contenido y bytes son evidencia de integridad, no sustituyen la lectura del documento.",
    "Cada XLSX se abrió con ExcelJS y se verificaron hojas, encabezados, todos los KPI, filas, totales",
    "significativos, gráficos, avisos, alertas, filtros legibles y celdas numéricas nativas.",
    "Cada PDF descargado se abrió con fitz si estuvo instalado y además con `pdftotext` independiente;",
    "se verificaron periodo en español, encabezados de tabla, totales significativos, caracteres",
    "`Página Día Participación →`, ausencia de U+FFFD/sustituciones ASCII y ausencia de JSON interno.",
    "fitz o pdftoppm confirmó renderización independiente; cuando se retuvieron artefactos se guardaron primera,",
    "una página de panel ancho o X04 y última para inspección visual. No se compara contra otro PDF del mismo generador.",
    "",
    "## Evidencia previa conservada",
    "",
    priorEvidence.length
      ? "Las dos filas normales completadas antes de este pase se conservaron literalmente como línea base:"
        + `\n${priorEvidence.join("\n")}`
      : "No había filas previas legibles; las dos vistas normales se incluyen en la tabla consolidada de este pase.",
    "",
    "## Matriz de autorización de Control",
    "",
    "| Ruta | non-ADMIN | ADMIN |",
    "|---|---:|---:|",
    ...(report.controlMatrix?.paths ?? []).map((path: string, index: number) =>
      `| \`${path}\` | ${report.controlMatrix.nonAdmin[index]} | ${report.controlMatrix.admin[index]} |`),
    "",
    "## Artefactos locales",
    "",
    report.artifacts.length
      ? report.artifacts.map((path: string) => `- \`${path}\` (modo 0600; bytes/hash están en la tabla anterior).`).join("\n")
      : "- No se retuvieron bytes; use `REPORT_EXPORT_WRITE_ARTIFACTS=1` para XLSX/PDF y páginas representativas 0600.",
    "- Intento bbox fallido conservado por separado en `reports/export-download-verification-bbox-failed.md`; sus diagnósticos sensibles quedaron reemplazados por hash.",
    "",
    "## Limitaciones y fallos históricos",
    "",
    `Fitz/PyMuPDF: ${report.fitzAvailable ? "disponible y utilizado" : "no disponible; no se instaló"}.`,
    "No se afirma descarga desde una aplicación desplegada ni autenticación de navegador.",
    "La numeración/mapa de los nueve fallos originales no es recuperable en este contexto; se deja",
    "deliberadamente para el agente propietario. La evidencia de este pase cubre el punto 8 de exports",
    "y la comprobación de permisos Control sin inventar una correspondencia numérica.",
    "",
  ];
  await writeFile(REPORT_PATH, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
  await chmod(REPORT_PATH, 0o600);
}

async function main(): Promise<void> {
  const writeArtifacts = process.env.REPORT_EXPORT_WRITE_ARTIFACTS === "1";
  if (writeArtifacts) {
    const { mkdir } = await import("node:fs/promises");
    await mkdir(EXPORT_DIR, { recursive: true, mode: 0o700 });
  }
  const priorEvidence = historicalEvidence();
  const started = Date.now();
  await withReadOnlySnapshot(async (query) => {
    const selected = await discoverYear(query);
    const comparisonSites = await discoverComparisonSites(query);
    const harness = await makeHarness();
    try {
      harness.setAuth("admin");
      if (comparisonSites.length !== 7) {
        throw new Error(`El catálogo real debe tener exactamente siete sitios elegibles para comparación; encontró ${comparisonSites.length}.`);
      }
      const base = {
        periodo: "personalizado",
        desde: `${selected.year}-01-01`,
        hasta: `${selected.year}-12-31`,
        modalidad: "TODO",
      };
      const cases: AnyRecord[] = [];
      const focus = (process.env.REPORT_EXPORT_FOCUS ?? "").split(",").map((value) => value.trim()).filter(Boolean);
      const requestedCases = focus.length
        ? focus
          .map((value) => {
            const match = value.match(/^(.*)-(normal|comparar)$/);
            const view = match?.[1];
            const mode = match?.[2];
            return view && VIEWS.includes(view as View) && (mode === "normal" || mode === "comparar")
              ? { view: view as View, mode: mode as CaseMode }
              : null;
          })
          .filter((item): item is { view: View; mode: CaseMode } => item !== null)
        : [
          ...VIEWS.map((view) => ({ view, mode: "normal" as const })),
          ...VIEWS.map((view) => ({ view, mode: "comparar" as const })),
        ];
      if (focus.length && requestedCases.length === 0) {
        throw new Error("REPORT_EXPORT_FOCUS no contiene casos válidos; usa ventas-normal,que-comprar-normal o control-operativo-normal.");
      }
      const errors: string[] = [];
      for (const requested of requestedCases) {
        try {
          cases.push(await verifyCase(
            harness,
            requested.view,
            requested.mode,
            base,
            comparisonSites,
            writeArtifacts,
          ));
        } catch (error) {
          const message = safeError(error);
          errors.push(`${requested.view}/${requested.mode}: ${message}`);
          cases.push({
            view: requested.view,
            mode: requested.mode,
            status: "FAILED",
            error: message,
          });
        }
      }
      let controlMatrix: AnyRecord = { paths: [], nonAdmin: [], admin: [] };
      try {
        controlMatrix = await assertControlRoleMatrix(harness, base);
      } catch (error) {
        errors.push(`control-role-matrix: ${safeError(error)}`);
      }
      const artifacts = cases.flatMap((item) => {
        if (!item.artifacts) return [];
        return [item.artifacts.xlsx, item.artifacts.pdf, ...(item.artifacts.representativePages ?? [])];
      });
      const passedCases = cases.filter((item) => item.status === "PASS");
      const fitzAvailable = passedCases.length > 0 && passedCases.every((item) => item.downloads.pdf.fitz === true);
      const report = {
        status: errors.length ? "HTTP_READ_ONLY_EXPORTS_COMPLETED_WITH_FAILURES" : "HTTP_READ_ONLY_EXPORTS_COMPLETED",
        snapshot: "single READ ONLY REPEATABLE READ connection",
        period: `${selected.year}-01-01/${selected.year}-12-31`,
        comparisonSiteCount: comparisonSites.length,
        cases,
        controlMatrix,
        artifacts,
        fitzAvailable,
        durationMs: Date.now() - started,
        errors,
        priorEvidence,
      };
      await writeReport(report);
      console.log(`Readonly export verification written: ${REPORT_PATH}`);
    } finally {
      await harness.close();
    }
  });
}

main().catch(async (error) => {
  const report = {
    status: "HTTP_READ_ONLY_EXPORTS_BLOCKED",
    snapshot: "single READ ONLY REPEATABLE READ connection",
    period: "not selected",
    comparisonSiteCount: 0,
    cases: [],
    controlMatrix: { paths: [], nonAdmin: [], admin: [] },
    artifacts: [],
    fitzAvailable: false,
    errors: [error instanceof Error ? error.message.slice(0, 2000) : "unknown"],
  };
  await writeReport(report).catch(() => undefined);
  console.error(`Readonly export verification blocked: ${report.errors[0]}`);
  process.exitCode = 1;
});