import fs from "node:fs";
import {spawnSync} from "node:child_process";
import {createHash} from "node:crypto";
const root="/home/runner/workspace", r=root+"/private.local/tanda-h-resume", s=r+"/frozen-source", report=root+"/reports/tanda-h/continuacion/setup";
function run(command,args,options={}){
 const x=spawnSync(command,args,{cwd:root,encoding:"utf8",timeout:180000,maxBuffer:16000000,...options});
 if(x.status!==0){fs.writeFileSync(r+"/build-error.txt",(x.stderr||"")+(x.stdout||""),{mode:0o600});throw Error(command+" failed; private diagnostics");}return x.stdout;
}
const hash=p=>createHash("sha256").update(fs.readFileSync(p)).digest("hex");
const commit=run("git",["rev-parse","HEAD"]).trim();
if(commit!=="b77bd7db4f97368433ef7dbce6e5c756b78b4452")throw Error("Unexpected source freeze");
if(fs.existsSync(s))throw Error("Frozen source already exists");
const tracked=run("git",["ls-tree","-r","--name-only",commit]).trim().split("\n");
const excluded=/^(reports|attached_assets|screenshots|\.agents)\//;
const files=tracked.filter(p=>!excluded.test(p)&&!/(^|\/)(dist[^/]*|node_modules)\//.test(p)&&!/\.(dump|tsbuildinfo)$/.test(p));
fs.mkdirSync(s,{recursive:true,mode:0o700});
run("git",["archive","--format=tar","--output="+r+"/source.tar",commit,"--",...files]);
run("tar",["-xf",r+"/source.tar","-C",s]);
const manifest=files.map(path=>({path,sha256:hash(s+"/"+path),workspaceMatches:fs.existsSync(root+"/"+path)&&hash(root+"/"+path)===hash(s+"/"+path)}));
fs.writeFileSync(report+"/source-files.json",JSON.stringify({commit,exclusions:"reports, attached_assets, screenshots, .agents, dist*, node_modules, dump, tsbuildinfo; tracked build/application source retained",files:manifest},null,2));
if(manifest.some(x=>!x.workspaceMatches))throw Error("Tracked workspace source differs from HEAD; frozen HEAD retained, stopping build");
let link=fs.readFileSync(root+"/reports/tanda-g/setup/link-frozen-dependencies.mjs","utf8");
link=link.replace('root+"/.local/tanda-g/"+(process.argv[2]==="candidate"?"candidate-source":"baseline-source")',JSON.stringify(s));
fs.writeFileSync(r+"/link.mjs",link,{mode:0o600});
run(process.execPath,[r+"/link.mjs"]);
run(process.execPath,[s+"/artifacts/api-server/build.mjs"],{cwd:s+"/artifacts/api-server",env:{PATH:process.env.PATH,HOME:r,NODE_ENV:"production"}});
run(process.execPath,[s+"/artifacts/mariana-textil/node_modules/vite/bin/vite.js","build"],{cwd:s+"/artifacts/mariana-textil",env:{PATH:process.env.PATH,HOME:r,NODE_ENV:"production",BASE_PATH:"/"}});
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(p+"/"+x.name):[p+"/"+x.name]);
const assets=[...walk(s+"/artifacts/api-server/dist"),...walk(s+"/artifacts/mariana-textil/dist/public")].map(p=>({path:p.slice(s.length+1),sha256:hash(p)}));
fs.writeFileSync(report+"/build-identity.json",JSON.stringify({commit,sourceArchiveSha256:hash(r+"/source.tar"),sourceManifestSha256:hash(report+"/source-files.json"),assets,applicationStarted:false,testsRun:false,dependencies:"Existing installed external packages symlinked; workspace packages resolve to frozen source",lockfileSha256:hash(s+"/pnpm-lock.yaml")},null,2));
console.log("Frozen HEAD source and API/UI builds hashed; no application started.");