const base = "artifacts/api-server/src/lib/";
const core = base + "e5.ts", repo = base + "e5-repository.ts", flag = base + "e5-feature.ts", http = base + "e5-http.ts";
const fund = base + "e5-fondo.ts", destination = base + "e5-destination-reader.ts", cash = base + "caja-cash-ledger.ts";
const metadata = "lib/db/src/schema/pos.ts";
const off = name => [name, flag, "export const E5_ENABLED = false;", "export const E5_ENABLED = true;"];
export default [
  off("E5-OFF-COMMAND"),
  off("E5-OFF-PREVIEW"),
  ["E5-OFF-HTTP", http, "if (E5_ENABLED) { next(); return; }", "if (true) { next(); return; }"],
  ["E5-OFF-AVAILABILITY", http, 'req.method === "GET"', 'req.method === "POST"'],
  ["E5-MONEY-POSITIVE", core, "BigInt(a!) * 100n + BigInt(b!)", "BigInt(a!) * 100n + BigInt(b!) * 10n"],
  ["E5-EXACT-MULTICHARGE", core, "const sum = notes.reduce((n, row) => n + e5Cents(row.saldoPendiente), 0n);", "const sum = e5Cents(notes[0]!.saldoPendiente);"],
  ["E5-EXACT-NONADMIN", core, 'if (actor.rol !== "ADMIN" && sum !== e5Cents(input.importe))', "if (false)"],
  ["E5-ALLOCATION-EXACT-MOVEMENT", core, "n.notaId === row.notaId && n.movimientoVentaId === row.movimientoVentaId", "n.notaId === row.notaId"],
  ["E5-ALLOCATION-NO-DUPLICATE", core, "if (seen.has(row.movimientoVentaId) || e5Cents(row.importe) <= 0n)", "if (e5Cents(row.importe) <= 0n)"],
  ["E5-RECEIVE-PERMISSION", core, '!(input.entrada === "CAJA" ? actor.recibirCaja : actor.recibirCliente)', "false"],
  ["E5-RECEIVE-SCOPE", core, 'if (actor.rol !== "ADMIN" && !(actor.ubicacionId === site || (!write && actor.todas && actor.ver)))', "if (false)"],
  ["E5-MEDIUM-SESSIONS", core, "(cash ? !input.sesionCajaId : !!input.sesionCajaId)", "false"],
  ["E5-ADMIN-APPLY-NOW", core, "if (value.aplicarAhora) {", "if (false) {"],
  ["E5-NONADMIN-NO-APPLY-NOW", core, 'if (input.aplicarAhora && actor.rol !== "ADMIN")', "if (false)"],
  ["E5-PROPOSAL-EXPLICIT-FUTURE", core, "detail.propuestas.push(proposal); detail.propuestaVigenteId = proposal.id;", 'detail.propuestas.push(proposal); detail.propuestaVigenteId = proposal.id; await apply(repo, detail, proposal, value.asignaciones, favor, context, actor, value.evidencia, now);'],
  ["E5-PREPARE-ADMIN-OR-A", core, "const a = E5_CONTADOR_A_ENABLED && actor.capacidadAE11 === true;", "const a = actor.rol === 'CONTADOR';"],
  ["E5-ADMIN-AUTHORIZE-NOW-CAPABILITY", core, "puedeAutorizar: admin && pending && (!detail || !!detail.propuestaVigenteId)", "puedeAutorizar: admin && pending && !!detail?.propuestaVigenteId"],
  ["E5-AUTHORIZE-ADMIN-ONLY", core, 'action !== "RECIBIR" && actor.rol !== "ADMIN"', "false"],
  ["E5-AUTHORIZE-SUBSET-ONLY", core, "e5Cents(row.importe) <= e5Cents(p.importe)", "true"],
  ["E5-PARTIAL-RESOLVES-PROPOSAL", core, 'detail.estado = e5Cents(detail.importePendiente) > 0n ? "PARCIAL" : "APLICADO";\n  delete detail.propuestaVigenteId;', 'detail.estado = e5Cents(detail.importePendiente) > 0n ? "PARCIAL" : "APLICADO";\n  // defect: proposal remains current'],
  ["E5-PAID-TARGET-FREEZES", core, "if (proposal.asignaciones.some(p => !context.notas.some", "if (false && proposal.asignaciones.some(p => !context.notas.some"],
  ["E5-REJECT-KEEPS-MONEY", core, "delete detail.propuestaVigenteId;\n      } else {", 'detail.importePendiente = "0.00"; delete detail.propuestaVigenteId;\n      } else {'],
  ["E5-FAVOR-EXPLICIT-ADMIN-ZERODEBT", core, "const amount = total(rows) + e5Cents(favor);", "const amount = total(rows);"],
  ["E5-FAVOR-NO-AUTO-WITH-DEBT", core, 'if (e5Cents(favor) > 0n && e5Cents(context.deudaGlobal) !== total(rows))', "if (false)"],
  ["E5-REFUND-NEVER-APPLIED-FULL", core, 'detail.importeDevuelto = detail.importeRecibido; detail.importePendiente = "0.00"; detail.estado = "DEVUELTO";', 'detail.importeDevuelto = "0.00"; detail.importePendiente = "0.00"; detail.estado = "DEVUELTO";'],
  ["E5-REFUND-AFTER-PARTIAL-NO", core, "if (detail.algunaVezAplicado || detail.aplicaciones.length || detail.importePendiente !== detail.importeRecibido || detail.devolucion)", "if (detail.devolucion)"],
  ["E5-IDEMPOTENCY-CONTENT", core, "prior.actorId !== actor.id || prior.content !== content", "prior.actorId !== actor.id"],
  ["E5-REVISION-CAS-MODEL", core, "if (detail.revision !== revision)", "if (false)"],
  ["E5-ROLLBACK-SYNTHETIC", core, "await repo.operation(input.claveOperacion, action, content, detail, actor);", 'if (action !== "RECIBIR") await repo.operation(input.claveOperacion, action, content, detail, actor);'],
  ["E5-TWO-DATES-AND-DOC-IMMUTABLE", core, "fechaEmision: application?.fechaAplicacion ?? detail.fechaRecepcion,", "fechaEmision: detail.fechaRecepcion,"],
  ["E5-ALERT-THREE-DAYS", core, "copy.antiguedadDias >= 3", "copy.antiguedadDias > 3"],
  ["E5-REFUND-PRIVACY", core, "delete copy.devolucion.fuente; delete copy.devolucion.salidaId; delete copy.devolucion.movimientoFondoId;", "delete copy.devolucion.salidaId;"],
  ["E5-RECEPTION-PAID-CHARGE-OMITTED", core, "notasIndicadas: context.notas.filter(n => value.notasIndicadas.includes(n.notaId) && e5Cents(n.saldoPendiente) > 0n),", "notasIndicadas: context.notas.filter(n => value.notasIndicadas.includes(n.notaId)),"],
  ["E5-DEPENDENCY-ERROR-SANITIZED", http, '(value.code === "23514" && value.constraint === "operaciones_productor_naturaleza_ck_e1")', "false"],
  ["E5-FUND-GUARD-OFF-NO-QUERY", fund, "if (!enabled) return;", "if (false) return;"],
  ["E5-FUND-INVERSE-GUARD", fund, "if (result.rows.length) {", "if (false) {"],
  ["E5-DESTINATION-OFF-NO-SQL", destination, 'if (!enabled) return "";', "if (false) return \"\";"],
  ["E5-DESTINATION-MONEY-ONLY", destination, "FROM e5_recepciones r", "FROM e5_aplicaciones r"],
  ["E5-CASH-RETAINED-WITHOUT-APPLICATION", cash, 'sums[document.origen] += amount;', 'sums[document.origen === "COBRO_RETENIDO" ? "ABONO" : document.origen] += amount;'],
  ["E5-DRIZZLE-PRODUCER-METADATA", metadata, "'E5_APLICACION_RETENIDA'", "'E5_APLICACION_LEGACY'"],
  ["E5-KEY-LOCK-REQUEST", repo, "pg_advisory_xact_lock(hashtextextended", "pg_try_advisory_xact_lock(hashtextextended"],
  ["E5-LOAD-FOR-UPDATE", repo, "ubicacion_id=${actor.ubicacionId}) FOR UPDATE", "ubicacion_id=${actor.ubicacionId})"],
  ["E5-SAVE-CAS", repo, "if (result.rows.length !== 1) throw", "if (false) throw"],
  ["E5-E1-CORRECT-PRODUCER", repo, "INSERT INTO operaciones_credito_e1(productor,clave,naturaleza,usuario_id,solicitud_canonica)\n        VALUES ('COBRO_PENDIENTE',${detail.id}::uuid,'INGRESO_FISICO'", "INSERT INTO operaciones_credito_e1(productor,clave,naturaleza,usuario_id,solicitud_canonica)\n        VALUES ('ABONO',${detail.id}::uuid,'INGRESO_FISICO'"],
  ["E5-APPLICATION-NO-SECOND-MONEY", repo, "async save(detail, oldRevision) {", "async save(detail, oldRevision) { await tx.execute(sql`INSERT INTO salidas_dinero_caja(sesion_caja_id,monto) VALUES (1,1)`);"],
  ["E5-LIST-SCOPE", repo, "e5Scope(actor, query.ubicacionId);", "// defect: list leaks other store"],
  ["E5-DOCUMENT-ADMIN-ONLY", repo, 'if (actor.rol !== "ADMIN") throw new E5Error("E5_FORBIDDEN", "Impresión exclusivamente ADMIN desde otro equipo.", 403);', "// defect: document disclosed"],
  ["E5-REFUND-OPTIONS-NO-ORIGINAL-CASH", repo, "for (const s of sessions.rows) sources.push", "for (const s of [{ id: 999, ubicacion_id: detail.ubicacionId }, ...sessions.rows]) sources.push"],
  ["E5-APPEND-AUDIT-PRIVATE", repo, "'FONDO',${\"E5_\" + action}", "'CAJA',${\"E5_\" + action}"],
];