import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import locationsRouter from "./locations";
import usersRouter from "./users";
import productosRouter from "./productos";
import proveedoresRouter from "./proveedores";
import clientesRouter from "./clientes";
import clientesAdminRouter from "./clientes-admin";
import clienteDocumentosRouter from "./cliente-documentos";
import permisosRouter from "./permisos";
import { inventarioRouter } from "./inventario";
import posRouter from "./pos";
import salidasRouter from "./salidas";
import adminAnalyticsRouter from "./admin-analytics";
import notificacionesRouter from "./notificaciones";
import etiquetasRouter from "./etiquetas";
import adminAlertasRouter from "./admin-alertas";
import reportesRouter from "./reportes";
import contenedoresRouter from "./contenedores";
import preciosRouter from "./precios";
import auditoriaRouter from "./auditoria";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(locationsRouter);
router.use(usersRouter);
router.use(productosRouter);
router.use(preciosRouter);
router.use(proveedoresRouter);
router.use(clientesAdminRouter);
router.use(clienteDocumentosRouter);
router.use(clientesRouter);
router.use(permisosRouter);
router.use("/inventario", inventarioRouter);
router.use(posRouter);
router.use(salidasRouter);
router.use(adminAnalyticsRouter);
router.use(adminAlertasRouter);
router.use(reportesRouter);
router.use(contenedoresRouter);
router.use(notificacionesRouter);
router.use(etiquetasRouter);
router.use(auditoriaRouter);

export default router;
