const base = "artifacts/api-server/src/lib/";
const core = base + "e9.ts", cut = base + "e9-cut.ts", repo = base + "e9-repository.ts", fund = base + "e9-fondo.ts", flag = base + "e9-feature.ts", http = base + "e9-http.ts";
const off = name => [name, flag, "export const E9_ENABLED = false;", "export const E9_ENABLED = true;"];
const authorizeGuard = 'if (detail.estado === "AUTORIZADA") throw new E9Error("E9_ALREADY_AUTHORIZED", "Ya existe recepción autorizada.");\n      const count = detail.conteos.at(-1);\n      if (detail.estado !== "CONTADA" || !count';
const authorizeDefect = 'const count = detail.conteos.at(-1);\n      if (!count';
export default [
  off("E9-OFF-WRITE"), off("E9-OFF-CUT"), off("E9-OFF-DETAIL"), off("E9-OFF-LIST"), off("E9-OFF-FUND-ORIGIN"), off("E9-OFF-INVERSE-READ"),
  ["E9-OFF-HTTP-OPTIONS", http, "if (E9_ENABLED) { next(); return; }", "if (true) { next(); return; }"],
  ["E9-OFF-HTTP-MUTATION", http, "if (E9_ENABLED) { next(); return; }", "if (true) { next(); return; }"],
  ["E9-CUT-CLOSED", cut, 'session.estado !== "CERRADA" || !session.cerradaAt', '!session.cerradaAt'],
  ["E9-CUT-NO-INFERENCE", cut, 'if (session.estado !== "CERRADA" || !session.cerradaAt || snapshots.length === 0) return undefined;',
    'if (snapshots.length === 0) return { corteId: session.id, versionCorte: "inventada", fechaCorte: String(session.cerradaAt), fechaOperativa: session.fechaOperativa, importeEnviado: session.efectivoContado! }; if (session.estado !== "CERRADA" || !session.cerradaAt) return undefined;'],
  ["E9-CUT-DUPLICATE", cut, "if (snapshots.length !== 1) throw", "if (false) throw"],
  ["E9-CUT-MISMATCH", cut, "if (snapshot.efectivoContado !== session.efectivoContado) throw", "if (false) throw"],
  ["E9-CUT-FULL-HASH", cut, "fechaCorte, snapshot,", "fechaCorte, snapshot: null,"],
  ["E9-CUT-PHYSICAL-NOT-SALES", cut, "importeEnviado: snapshot.efectivoContado", "importeEnviado: snapshot.efectivoDesglose.cobrosTickets"],
  ["E9-CUT-ORIGINAL-PERIOD", cut, "fechaOperativa: session.fechaOperativa, fechaCorte, snapshot,", "fechaOperativa: null, fechaCorte, snapshot,"],
  ["E9-DECIMAL", core, "BigInt(whole!) * 100n + BigInt(part!)", "BigInt(whole!) * 100n + BigInt(part!) * 10n"],
  ["E9-NO-PARTIAL-INPUT", core, 'versionCorte: z.string().min(1).max(200), evidencia: e9Evidence }).strict();', 'versionCorte: z.string().min(1).max(200), evidencia: e9Evidence }).passthrough();'],
  ["E9-SEND-COMPLETE", core, 'detail = { ...cut, id: randomUUID(),', 'detail = { ...cut, importeEnviado: "5.00", id: randomUUID(),'],
  ["E9-SEND-SCOPE", core, 'actor.rol !== "ADMIN" && actor.ubicacionId !== site', "false"],
  ["E9-SEND-ROLE", core, '!["ADMIN", "SUPERVISOR"].includes(actor.rol)', '!["ADMIN", "SUPERVISOR", "CAJA"].includes(actor.rol)'],
  ["E9-SEND-PERMISSION", core, 'action === "ENVIAR" && actor.puedeEnviar !== true', "false"],
  ["E9-CUT-VERSION", core, "if (cut.versionCorte !== value.versionCorte)", "if (false)"],
  ["E9-CUT-ZERO", core, "if (e9Cents(cut.importeEnviado) <= 0n)", "if (e9Cents(cut.importeEnviado) < 0n)"],
  ["E9-CUT-ONCE", core, "if (await repo.sent(cut.corteId))", "if (false)"],
  ["E9-REPLAY", core, "if (previous) {", "if (false) {"],
  ["E9-REPLAY-CONTENT", core, "previous.actorId !== actor.id || previous.content !== content", "previous.actorId !== actor.id"],
  ["E9-CONCURRENT-SEND-MODEL", core, "if (await repo.sent(cut.corteId))", "if (false)"],
  ["E9-COUNT-ADMIN", core, ': actor.rol !== "ADMIN")\n    throw', ': false)\n    throw'],
  ["E9-COUNT-DEFICIT", core, 'if (count.diferencia !== "0.00" && !detail.investigacion)', 'if (!count.diferencia.startsWith("-") && count.diferencia !== "0.00" && !detail.investigacion)'],
  ["E9-COUNT-SURPLUS", core, 'if (count.diferencia !== "0.00" && !detail.investigacion)', 'if (count.diferencia.startsWith("-") && !detail.investigacion)'],
  ["E9-COUNT-ZERO", core, 'if (count.diferencia !== "0.00" && !detail.investigacion)', 'if (count.importeRecibido !== "0.00" && count.diferencia !== "0.00" && !detail.investigacion)'],
  ["E9-COUNT-HISTORY", core, "detail.conteos.push(count);", "detail.conteos = [count];"],
  ["E9-STALE-COUNT", core, 'detail.estado !== "CONTADA" || !count || count.id !== value.conteoId || detail.conteoVigenteId !== count.id', 'detail.estado !== "CONTADA" || !count'],
  ["E9-ZERO-NO-SEAT", core, "if (e9Cents(count.importeRecibido) <= 0n)", "if (e9Cents(count.importeRecibido) < 0n)"],
  ["E9-AUTH-ROLE", core, ': actor.rol !== "ADMIN")\n    throw', ': false)\n    throw'],
  ["E9-AUTH-EXACT", core, "repo.income(detail, count.importeRecibido, input.claveOperacion, actor)", "repo.income(detail, detail.importeEnviado, input.claveOperacion, actor)"],
  ["E9-AUTH-REASON", core, 'if (count.diferencia !== "0.00" && !value.motivo)', "if (false)"],
  ["E9-AUTH-ONCE", core, authorizeGuard, authorizeDefect],
  ["E9-CONCURRENT-AUTH-MODEL", core, authorizeGuard, authorizeDefect],
  ["E9-AUTH-ROLLBACK-MODEL", core, "await repo.operation(input.claveOperacion, action, content, detail, actor);", 'if (action !== "AUTORIZAR") await repo.operation(input.claveOperacion, action, content, detail, actor);'],
  ["E9-RECOUNT-AUTHORIZED", core, 'if (detail.estado === "AUTORIZADA") throw new E9Error("E9_ALREADY_AUTHORIZED", "La recepción ya está autorizada.");', "// defect: permit recount after income"],
  ["E9-CLOSE-ROLE", core, ': actor.rol !== "ADMIN")\n    throw', ': false)\n    throw'],
  ["E9-CLOSE-NONFINANCIAL", core, 'detail.investigacion.estado = "CERRADA_DOCUMENTAL";', 'detail.importeEnviado = detail.autorizacion!.importeRecibido; detail.investigacion.estado = "CERRADA_DOCUMENTAL";'],
  ["E9-CLOSE-EVIDENCE", core, "const text = z.string().trim().min(1).max(2000);", "const text = z.string().trim().min(0).max(2000);"],
  ["E9-CLOSE-STATE", core, 'if (detail.estado !== "AUTORIZADA" || detail.investigacion?.estado !== "ABIERTA")', 'if (detail.investigacion?.estado !== "ABIERTA")'],
  ["E9-CLOSE-ONCE", core, 'if (detail.estado !== "AUTORIZADA" || detail.investigacion?.estado !== "ABIERTA")', 'if (detail.estado !== "AUTORIZADA")'],
  ["E9-PRIVACY", core, 'if (actor.rol !== "ADMIN") delete result.fondo;', "// defect: disclose Fondo to store"],
  ["E9-CAS", repo, "if (result.rows.length !== 1) throw", "if (false) throw"],
  ["E9-KEY-LOCK", repo, "pg_advisory_xact_lock(hashtextextended", "pg_try_advisory_xact_lock(hashtextextended"],
  ["E9-RECEIPT-LOCK-REQUEST", repo, "SELECT revision,detail FROM e9_entregas WHERE id=${id}::uuid FOR UPDATE", "SELECT revision,detail FROM e9_entregas WHERE id=${id}::uuid"],
  ["E9-CUT-LOCK-REQUEST", repo, "FOR UPDATE OF s", "FOR SHARE OF s"],
  ["E9-LIST-SCOPE", repo, "e9Scope(actor, query.ubicacionId);", "// defect: allow other store query"],
  ["E9-INVERSE-GUARD", fund, "if (result.rows.length) throw", "if (false) throw"],
  ["E9-FUND-ORIGIN", fund, "corteHref: `/caja/cortes?sesionId=${row.corte_id}`", "corteHref: `/caja/cortes?sesionId=${row.corte_id + 1}`"],
  ["E9-AUDIT-PRIVACY", repo, "'FONDO',${'E9_' + action}", "'CAJA',${'E9_' + action}"],
  ["E9-FUND-ACTUAL-CALLER-TX", repo, "async income(detail, amount, key, actor) {\n      const result", "async income(detail, amount, key, actor) {\n      await tx.execute(sql`COMMIT`);\n      const result"],
  ["E9-FUND-ACTUAL-AMOUNT", repo, 'categoria: "OTRO_INGRESO", importe: amount,', 'categoria: "OTRO_INGRESO", importe: "9.00",'],
  ["E9-NO-SECOND-CASH-WITHDRAWAL", repo, "async save(detail, revision) {", "async save(detail, revision) {\n      await tx.execute(sql`UPDATE sesiones_caja SET efectivo_contado=0 WHERE id=${detail.corteId}`);"],
];