const lib = "artifacts/api-server/src/lib/";
const model = lib + "e7-read-model.ts";
const scope = lib + "clientes-cartera-read-model.ts";
const exporter = lib + "e7-export.ts";

export default [
  ["E7-OFF-NO-READS", model,
    "if (!options.enabled) throw new E7Error(\"E7_DISABLED\", \"E7 no está habilitado.\", 403);",
    "if (false) throw new E7Error(\"E7_DISABLED\", \"E7 no está habilitado.\", 403);"],
  ["E7-E5-DEPENDENCY-NO-FALLBACK", model,
    "if (!options.e5Enabled) throw new E7Error(\"E7_DEPENDENCIA_NO_DISPONIBLE\", \"Falta habilitación de la fuente E5; no se fabrica cero.\");",
    "if (false) throw new E7Error(\"E7_DEPENDENCIA_NO_DISPONIBLE\", \"Falta habilitación de la fuente E5; no se fabrica cero.\");"],
  ["E7-SESSION-MUST-BE-CURRENT", model,
    "if (!user) throw new E7Error(\"NO_AUTENTICADO\", \"Sesión no vigente.\", 401);",
    "if (false) throw new E7Error(\"NO_AUTENTICADO\", \"Sesión no vigente.\", 401);"],
  ["E7-CONTADOR-A-F-HARD-DENY", model,
    "if (user.rol === \"CONTADOR\") throw new E7Error(\"PERFIL_DENEGADO\", \"CONTADOR utiliza exclusivamente las proyecciones E11 autorizadas.\", 403);",
    "if (false) throw new E7Error(\"PERFIL_DENEGADO\", \"CONTADOR utiliza exclusivamente las proyecciones E11 autorizadas.\", 403);"],
  ["E7-CENTRAL-PERMISSION-AND-SITE-SCOPE", scope,
    "if (unrestricted.ubicacionId != null) {\n    if (requested.length !== 1 || requested[0] !== unrestricted.ubicacionId)",
    "if (false) {\n    if (requested.length !== 1 || requested[0] !== unrestricted.ubicacionId)"],
  ["E7-REAUTHORIZES-BEFORE-DELIVERY", model,
    "if (JSON.stringify(current) !== JSON.stringify(auth)) throw new E7Error(\"PERFIL_CAMBIADO\", \"Cambió el alcance antes de entregar.\", 403);",
    "if (false) throw new E7Error(\"PERFIL_CAMBIADO\", \"Cambió el alcance antes de entregar.\", 403);"],
  ["E7-FOUR-GLOBALS-SITE-DETAIL", model,
    "resumenGlobal: { deudaActual: safeMoney(data.projection.balanceCents)",
    "resumenGlobal: { deudaActual: safeMoney(0)"],
  ["E7-CANONICAL-FIFO-PORTIONS", model,
    "projectCreditLedger(ledger, { includeMovementProjections: true, includeAllocationTraces: true })",
    "projectCreditLedger(ledger, { includeMovementProjections: true, includeAllocationTraces: false })"],
  ["E7-RECEIPT-APPLICATION-NOT-DOUBLE-INCOME", model,
    "![\"APLICACION\", \"REVERSO_APLICACION\"].includes(m.tipo)",
    "true || ![\"APLICACION\", \"REVERSO_APLICACION\"].includes(m.tipo)"],
  ["E7-RETAINED-STOCK-NOT-RANGE-FLOW", model,
    "(r.importe-COALESCE(a.importe,0)-COALESCE(d.importe,0))::text AS pendiente",
    "r.importe::text AS pendiente"],
  ["E7-HISTORIC-51-53-UNLOCATED-GLOBAL-ONLY", model,
    "CASE WHEN m.id IN (51,52,53) THEN NULL ELSE m.sitio_origen_id END AS sitio_origen_id",
    "CASE WHEN m.id IN (51,52) THEN NULL ELSE m.sitio_origen_id END AS sitio_origen_id"],
  ["E7-MISSING-MONETARY-SOURCE-FAILS", model,
    "if (meta.account === null)\n              throw new E7Error(\"E7_FUENTE_INVALIDA\", \"Cobranza sin cuenta documentada; no se inventa destino.\");",
    "if (false)\n              throw new E7Error(\"E7_FUENTE_INVALIDA\", \"Cobranza sin cuenta documentada; no se inventa destino.\");"],
  ["E7-STATEMENT-REAL-DOCUMENTS-AND-LEGENDS", exporter,
    "function headings(data: E7Statement) {\n  return [\n    ...data.leyendas,",
    "function headings(data: E7Statement) {\n  return ["],
  ["E7-ATTRIBUTION-REAL-DOCUMENTS-AND-LEGENDS", exporter,
    "function attributionHeadings(data: E7Attribution) {\n  return [\n    ...data.leyendas,",
    "function attributionHeadings(data: E7Attribution) {\n  return ["],
];