// MAIN-only --import preload for the *separate* disposable API process.
// Only E11 period evaluation advances: auth/session time and SQL clocks stay real.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { isMainThread } from "node:worker_threads";
import { registerHooks } from "node:module";
import { pathToFileURL } from "node:url";

// Node workers inherit --import. Leave logger worker clocks and modules untouched.
if (isMainThread) {
const root = resolve("private.local/roll-return-continuation");
const expected = `postgresql://postgres@127.0.0.1:55536/continue_test`;
const witness = `postgresql://postgres@127.0.0.1:55536/continue_witness`;
const marker = JSON.parse(readFileSync(`${root}/ownership-marker.json`, "utf8"));
const ready = JSON.parse(readFileSync("reports/continuacion-rollos-20260925/preparation/ready.json", "utf8"));
if (marker.owner !== "MAIN" || marker.root !== root || marker.port !== 55536 ||
    ready.owner !== "MAIN" || ready.testDatabase !== "continue_test" ||
    process.argv[1] !== `${root}/api.mjs` ||
    process.env.FISCAL_CLOCK_READY !== "MAIN_STARTED_FORWARD_ONLY" ||
    process.env.DATABASE_URL !== expected ||
    process.env.APPLICATION_DATABASE_URL !== witness ||
    process.env.PORT !== "43940" ||
    process.env.NODE_ENV !== "development" ||
    process.env.API_INSPECTION_BOOT !== "1" ||
    process.env.TEST_DATABASE_URL ||
    process.env.REQUIRE_ISOLATED_TEST_DATABASE)
  throw Error("Refusing forward test clock: isolated API identity, readiness, or explicit MAIN authorization mismatch");

const RealDate = Date;
const fixedInstant = "2026-11-02T18:00:00.000Z";
const fixed = RealDate.parse(fixedInstant);
if (!(fixed > RealDate.now()) || new RealDate().toISOString().slice(0, 10) !== "2026-09-25")
  throw Error("Refusing non-forward/resumed real clock or wrong source date");
// The global Date shim made login fail: sesiones.created_at is generated by the
// real PostgreSQL clock, and E11 requires a session created within 16 hours.
// Transform ONLY the two E11 period-clock calls in the disposable bundle in
// memory; never edit the app, auth logic, session rows, SQL clocks or global Date.
const bundle = pathToFileURL(`${root}/source/artifacts/api-server/dist/index.mjs`).href;
const calls = [
  [
    "const period2 = e11Period(input.tipo, input.inicio, e11Runtime().now());",
    `const period2 = e11Period(input.tipo, input.inicio, new Date("${fixedInstant}"));`,
  ],
  [
    "all.push(previous ? (await e11Snapshot(tx, String(previous.id))).periodo : e11Period(kind, day2, e11Runtime().now()));",
    `all.push(previous ? (await e11Snapshot(tx, String(previous.id))).periodo : e11Period(kind, day2, new Date("${fixedInstant}")));`,
  ],
];
registerHooks({
  load(url, context, nextLoad) {
    const loaded = nextLoad(url, context);
    if (url !== bundle) return loaded;
    let source = String(loaded.source);
    for (const [original, replacement] of calls) {
      if (source.split(original).length !== 2)
        throw Error("Refusing isolated fiscal clock: expected unique E11 period call absent or changed");
      source = source.replace(original, replacement);
    }
    return { ...loaded, source };
  },
});
}