// Generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prompt-k-clientes/CurrentProveedores.tsx": () => import("./../components/mockups/prompt-k-clientes/CurrentProveedores.tsx"),
  "./components/mockups/prompt-k-clientes/PropuestaClientes.tsx": () => import("./../components/mockups/prompt-k-clientes/PropuestaClientes.tsx")
};
