import fs from "node:fs";
import assert from "node:assert/strict";
assert.equal(process.env.MAIN_READY, "yes", "Wait for MAIN readiness");
const c = JSON.parse(fs.readFileSync(process.env.INVENTORY_HANDOFF, "utf8"));
const url = new URL(c.databaseUrl);
assert.equal(url.hostname, "127.0.0.1");
assert.match(c.databaseName, /^tanda_ga_inventory(?:_[a-z0-9]+)*$/);
assert.equal(url.pathname, `/${c.databaseName}`);
process.env.DATABASE_URL = "postgresql://postgres@127.0.0.1:55442/tanda_ga_witness";
process.env.APPLICATION_DATABASE_URL = process.env.DATABASE_URL;
process.env.TEST_DATABASE_URL = c.databaseUrl;
process.env.NODE_ENV = "test";
process.env.REQUIRE_ISOLATED_TEST_DATABASE = "1";
await import(process.env.INVENTORY_CHAINS === "yes" ? "./chains.bundle.mjs" : "./matrix.bundle.mjs");