const lib = "artifacts/api-server/src/lib/";
const core = lib + "e11.ts", repo = lib + "e11-repository.ts", feature = lib + "e11-feature.ts";
const e5 = lib + "e5.ts";
export default [
  ["E11-OFF-ALL-GATES", feature, "export const E11_ENABLED: boolean = false;", "export const E11_ENABLED: boolean = true;"],
  ["E11-OFF-SECURITY-NO-SQL", repo, "export async function e11SecurityLock(tx: E11Sql, exclusive = false) {\n  if (!e11Runtime().flags.enabled) return;", "export async function e11SecurityLock(tx: E11Sql, exclusive = false) {\n  if (false) return;"],
  ["E11-OFF-ROLE-CHANGE-NO-SQL", repo, "export async function e11UserRoleChange(tx: E11Sql, userId: number, nextRole: string, nextActive: boolean, actorId: number) {\n  if (!e11Runtime().flags.enabled) return;", "export async function e11UserRoleChange(tx: E11Sql, userId: number, nextRole: string, nextActive: boolean, actorId: number) {\n  if (false) return;"],
  ["E11-CANONICAL-KEY-ORDER", core, ".sort(([a], [b]) => a.localeCompare(b))", ".sort(([a], [b]) => b.localeCompare(a))"],
  ["E11-HASH-CONTENT-SENSITIVE", core, "createHash(\"sha256\").update(e11Canonical(value)).digest(\"hex\")", "createHash(\"sha256\").update(\"constant\").digest(\"hex\")"],
  ["E11-MONEY-EXACT-CENTS", core, "return BigInt(value.replace(\".\", \"\"));", "return BigInt(value.replace(\".\", \"\")) * 10n;"],
  ["E11-MONEY-REJECTS-NONCANONICAL", core, "if (!/^-?\\d+\\.\\d{2}$/.test(value))", "if (!/^-?\\d+(?:\\.\\d{1,2})?$/.test(value))"],
  ["E11-CALENDAR-DAY-OPTIONAL", core, "obligatorio: tipo !== \"DIA\"", "obligatorio: true"],
  ["E11-CALENDAR-WEEK-MONDAY", core, "tipo === \"SEMANA\" && d.getUTCDay() !== 1", "tipo === \"SEMANA\" && d.getUTCDay() !== 2"],
  ["E11-CALENDAR-MONTH-BOUNDARY", core, "tipo === \"MES\" && d.getUTCDate() !== 1", "tipo === \"MES\" && d.getUTCDate() !== 2"],
  ["E11-CALENDAR-NO-DEADLINES", core, "ultimaConciliacionId: null as string | null", "ultimaConciliacionId: null as string | null, vencimiento: e11Advance(inicio, 10)"],
  ["E11-PERIOD-OPEN", core, "e11Date(finExclusivo) > now ? \"ABIERTO\" : \"PENDIENTE\"", "e11Date(finExclusivo) < now ? \"ABIERTO\" : \"PENDIENTE\""],
  ["E11-RANGE-NONEMPTY", core, "if (start >= end)", "if (start > end)"],
  ["E11-ADVANCE-CALENDAR", core, "d.setUTCDate(d.getUTCDate() + days)", "d.setUTCDate(d.getUTCDate() + days + 1)"],
  ["E11-CAPABILITY-EXPLICIT", core, "if (!identity.capacidades.includes(capability))", "if (false)"],
  ["E11-CURSOR-BINDS-IDENTITY-VERSION", core, "const scope = e11Hash({ identity, filters, revision });", "const scope = e11Hash({ filters, revision });"],
  ["E11-CURSOR-BINDS-FILTERS", core, "const scope = e11Hash({ identity, filters, revision });", "const scope = e11Hash({ identity, revision });"],
  ["E11-CURSOR-BINDS-SOURCE", core, "const scope = e11Hash({ identity, filters, revision });", "const scope = e11Hash({ identity, filters });"],
  ["E11-PAGINATION-LIMIT", core, "const end = offset + query.limit;", "const end = items.length;"],
  ["E11-REPLAY-LOCK-NAMESPACE", repo, "const key = `${actor.usuarioId}:${operation}:${uuid.toLowerCase()}`;", "const key = `${actor.usuarioId}:${uuid.toLowerCase()}`;"],
  ["E11-REPLAY-SAME-BODY-NO-WORK", repo, "return prior.respuesta as T;", "return work();"],
  ["E11-REPLAY-DIFFERENT-BODY-DENIED", repo, "if (prior.solicitud_hash !== hash)", "if (false)"],
  ["E11-FISCAL-FACTURADO-NOT-COBRADO", repo, "WHERE t.facturado=true AND ${sql.raw(accountedDocumentPredicate(\"t\"))}\n    ${range", "WHERE t.facturado=false AND ${sql.raw(accountedDocumentPredicate(\"t\"))}\n    ${range"],
  ["E11-FISCAL-DTO-WHITELIST", repo, "totalFacturado: String(row.total), moneda: \"MXN\", estado: \"VIGENTE\"", "totalFacturado: String(row.total), moneda: \"MXN\", estado: \"VIGENTE\", saldo: String(row.saldo)"],
  ["E11-FISCAL-TOTAL-ALL-DOCUMENTS", repo, "items.reduce((sum, item) => sum + e11Cents(item.totalFacturado), 0n)", "e11Cents(items[0]?.totalFacturado ?? \"0.00\")"],
  ["E11-FISCAL-CLIENTS-DISTINCT-SOURCE", repo, "SELECT DISTINCT c.id,c.nombre FROM clientes c JOIN tickets t", "SELECT c.id,c.nombre FROM clientes c JOIN tickets t"],
  ["E11-PROFILE-HISTORY-APPEND-ORDER", repo, "ORDER BY revision,id", "ORDER BY revision DESC,id"],
  ["E11-SNAPSHOT-SOURCE-CHANGE-REQUIRES-REVISION", repo, "latest?.id === id && current.fuenteRevision === snapshot.fuenteRevision", "latest?.id === id"],
  ["E11-SNAPSHOT-FROZEN-SALES", repo, "SELECT datos FROM e11_conciliacion_ventas WHERE conciliacion_id=${id}::uuid ORDER BY venta_id", "SELECT datos FROM e11_conciliacion_ventas WHERE conciliacion_id=${id}::uuid AND false ORDER BY venta_id"],
  ["E11-SNAPSHOT-EVIDENCE-CAS", repo, "if (e11Hash(items) !== snapshot.evidenciaHash)", "if (false)"],
  ["E11-PERIOD-LIST-SEPARATE-OBLIGATIONS", repo, "for (const kind of [\"DIA\", \"SEMANA\", \"MES\"] as E11PeriodType[])", "for (const kind of [\"DIA\"] as E11PeriodType[])"],
  ["E11-IDENTITY-CONTADOR-DEFAULT-F", repo, "(row?.perfil === \"A\" ? \"A\" : \"F\")", "(row?.perfil === \"F\" ? \"F\" : \"A\")"],
  ["E11-IDENTITY-A-EXPLICIT-CURRENT-VERSION", repo, "perfilVersion: Number(row?.version ?? 0)", "perfilVersion: 0"],
  ["E11-ASSIGN-ADMIN-CAS-HISTORY", repo, "await e11WriteProfileEvent(tx, event);\n    return event;", "return event;"],
  ["E11-ASSIGN-STALE-CAS-NO-WRITE", repo, "if (Number(prior?.version ?? 0) !== input.revisionEsperada)", "if (false)"],
  ["E11-ROLE-CHANGE-REVOKES-A", repo, "const profile = nextRole === \"CONTADOR\" && nextActive ? \"F\" : null;", "const profile = nextActive ? \"F\" : null;"],
  ["E11-ROLE-REENTRY-STARTS-F", repo, "nextRole === \"CONTADOR\" && nextActive ? \"F\" : null", "nextRole === \"CONTADOR\" && nextActive ? (prior?.perfil ?? \"F\") : null"],
  ["E11-RECOVERY-QUERY-PENDING-NOT-404", repo, ": \"PENDIENTE\" as const,\n    resolucionId:", ": \"CONFIRMADA\" as const,\n    resolucionId:"],
  ["E11-RECOVERY-NORMALIZES-ORIGINAL-UUID", repo, "uuidOriginal: z.string().uuid().transform(s => s.toLowerCase())", "uuidOriginal: z.string().uuid()"],
  ["E11-RECOVERY-USES-PRODUCER-REPLAY-NAMESPACE", repo, "`E11:${target.actorId}:${target.accion}:${target.uuidOriginal}`", "`E11:recovery:${target.actorId}:${target.accion}:${target.uuidOriginal}`"],
  ["E11-RECOVERY-REQUIRES-FRESH-ADMIN", repo, "if (actor.rolBase !== \"ADMIN\") throw new E11Error(\"ADMIN_REQUERIDO\", \"Sólo ADMIN real resuelve intenciones.\", 403);", "if (false) throw new E11Error(\"ADMIN_REQUERIDO\", \"Sólo ADMIN real resuelve intenciones.\", 403);"],
  ["E11-RECOVERY-RESOLVE-WRITES-TOMBSTONE-NO-EFFECT", repo, "if (current.estado === \"PENDIENTE\") {\n    // Unique PK shared with producers", "if (false) {\n    // Unique PK shared with producers"],
  ["E11-RECOVERY-RESOLVE-CONFIRMED-WITHOUT-TOMBSTONE", repo, "estado: current.estado === \"PENDIENTE\" ? \"CERRADA_SIN_EFECTO\" as const : current.estado", "estado: \"CERRADA_SIN_EFECTO\" as const"],
  ["E11-RECOVERY-RESOLVE-REJECTS-STALE-ADMIN-VERSION", repo, "if (actor.permisosVersion !== input.identidadVersion)", "if (false)"],
  ["E11-RECOVERY-RESOLVE-CAS-NO-WRITE", repo, "if (current.revision !== input.revisionEsperada || current.resolucionId)", "if (current.resolucionId)"],
  ["E11-RECOVERY-RESOLUTION-REPLAY-IDEMPOTENT", repo, "return E11RecoveryOutput.parse(replay.respuesta);", "void E11RecoveryOutput.parse(replay.respuesta);"],
  ["E11-RECOVERY-TOMBSTONE-BLOCKS-LATE-REQUEST", repo, "if (prior.estado === \"CERRADA_SIN_EFECTO\")", "if (false)"],
  ["E11-RECOVERY-POSTCOMMIT-PRIVATE-NONRECURSIVE", core, "export const e11ErrorBody = (error: E11Error) => ({\n  code: error.code", "export const e11ErrorBody = (error: E11Error) => ({\n  ...error, code: error.code"],
  ["E11-RECOVERY-TARGET-REJECTS-RECURSIVE-QUARANTINE", repo, "z.enum([\"PERFIL\", \"SNAPSHOT\", \"DECISION\", \"PREPARACION\"])", "z.enum([\"PERFIL\", \"SNAPSHOT\", \"DECISION\", \"PREPARACION\", \"RESOLUCION\"])"],
  ["E11-EXECUTE-REAUTH-DENIES-REVOKED-DELIVERY", repo, "if (e11Hash(current) !== e11Hash(result.identity))\n        throw new E11Error(\"PERFIL_CAMBIADO\", \"El perfil cambió antes de responder.\");\n      if (command.capability) e11Capability(current, command.capability);", "if (false)\n        throw new E11Error(\"PERFIL_CAMBIADO\", \"El perfil cambió antes de responder.\");\n      if (false) e11Capability(current, command.capability!);"],
  ["E11-EXECUTE-PARSE-FAILS-FIRST-TRANSACTION", repo, "try { payload = command.parse(value); }", "try { payload = value as T; }"],
  ["E11-EXECUTE-DELIVER-FAILS-AFTER-COMMIT", repo, "await command.deliver(result.payload, current);", "await Promise.resolve();"],
  ["E11-NO-CUADRA-NOTIFICATION-ROLLBACK-RETRY", repo, "await tx.execute(sql`INSERT INTO notificaciones_sistema", "if (false) await tx.execute(sql`INSERT INTO notificaciones_sistema"],
  ["E11-NO-CUADRA-REPLAY-NO-DOUBLE-NOTIFICATION", repo, "return prior.respuesta as T;", "return work();"],
  ["E11-A-PREPARES-REAL-E5-PROPOSAL-ONLY", repo, "actor, \"PROPONER\", {", "actor, \"AUTORIZAR\", {"],
  ["E11-A-PREPARATION-DUPLICATE-NOTES-DENIED", repo, "if (new Set(input.asignaciones.map(a => a.notaId)).size !== input.asignaciones.length)", "if (false)"],
  ["E11-LEGACY-DEFAULT-DENY-POLICY", "artifacts/api-server/src/middlewares/e11-legacy.ts", "[\"/auth/me\", \"/auth/logout\"].includes(path)", "[\"/auth/me\", \"/auth/logout\", \"/clientes\"].includes(path)"],
  ["E11-LEGACY-BOUNDARY-AUTHENTICATES-THEN-DENIES", "artifacts/api-server/src/middlewares/e11-legacy.ts", "if (!e11LegacyAllowed(enabled, req.auth?.user.rol, req.path))", "if (false)"],
  ["E11-E5-A-CLOSED-WHILE-OFF", e5, "const a = e11Runtime().flags.e5Enabled && e11Runtime().flags.e5ContadorA\n    && e11Runtime().flags.enabled && e11Runtime().flags.preparation", "const a = true"],
  ["E11-ERROR-BODY-IS-PRIVATE", core, "export const e11ErrorBody = (error: E11Error) => ({\n  code: error.code", "export const e11ErrorBody = (error: E11Error) => ({\n  ...error, code: error.code"],
];